"""
Template Generator - Agent Markdown ve Settings Generasyonu

Agent genome'undan .md dosyalari ve settings.json guncellemeleri olusturur.
"""

import json
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Optional

from .agent_genome import AgentGenome, AgentModel, Capability


@dataclass
class GenerationResult:
    """Generasyon sonucu"""
    success: bool
    file_path: Optional[str] = None
    error: Optional[str] = None
    generated_at: datetime = None

    def __post_init__(self):
        if self.generated_at is None:
            self.generated_at = datetime.now()


class TemplateGenerator:
    """
    Agent template ve settings dosyalari olusturucu

    Gorevler:
    - Agent genome'undan .md dosyasi olustur
    - settings.json'a yeni agent ekle
    - Mevcut agent'lari guncelle
    """

    def __init__(self, base_path: str = ".claude"):
        self.base_path = Path(base_path)
        self.agents_dir = self.base_path / "agents"
        self.settings_file = self.base_path / "settings.json"

    async def generate_agent_markdown(
        self,
        genome: AgentGenome,
        output_dir: Optional[Path] = None
    ) -> GenerationResult:
        """
        Agent genome'undan .md template olustur

        Args:
            genome: Agent genome
            output_dir: Cikti klasoru (default: .claude/agents)

        Returns:
            GenerationResult
        """
        try:
            target_dir = output_dir or self.agents_dir
            target_dir.mkdir(parents=True, exist_ok=True)

            # Build markdown content
            md_content = self._build_markdown(genome)

            # Write file
            file_name = self._sanitize_filename(genome.name)
            file_path = target_dir / f"{file_name}.md"
            file_path.write_text(md_content, encoding="utf-8")

            return GenerationResult(
                success=True,
                file_path=str(file_path),
            )

        except Exception as e:
            return GenerationResult(
                success=False,
                error=str(e),
            )

    def _build_markdown(self, genome: AgentGenome) -> str:
        """Markdown icerigi olustur"""
        # Tools string
        tools_str = ", ".join(genome.tools) if genome.tools else "All tools"

        # Model string
        model_str = genome.model.value if genome.model != AgentModel.INHERIT else "inherit"

        # Frontmatter
        frontmatter = f"""---
name: {genome.name}
description: {self._get_description(genome)}
tools: {tools_str}
model: {model_str}
version: {genome.version}
generated: true
agent_id: {genome.agent_id}
---"""

        # Capabilities section
        capabilities_section = self._build_capabilities_section(genome)

        # System prompt section
        system_prompt_section = f"""## System Prompt

```
{genome.system_prompt}
```"""

        # Configuration section
        config_section = f"""## Configuration

| Parameter | Value |
|-----------|-------|
| Temperature | {genome.temperature} |
| Max Tokens | {genome.max_tokens} |
| Learning Rate | {genome.learning_params.learning_rate} |
| Exploration Rate | {genome.learning_params.exploration_rate} |
| Memory Size | {genome.learning_params.memory_size} |"""

        # Performance section
        perf_section = f"""## Performance Metrics

| Metric | Value |
|--------|-------|
| Total Tasks | {genome.metrics.total_tasks} |
| Successful Tasks | {genome.metrics.successful_tasks} |
| Success Rate | {genome.metrics.success_rate:.1%} |
| Avg Response Time | {genome.metrics.avg_response_time_ms:.0f}ms |
| Fitness Score | {genome.fitness_score:.2f} |"""

        # Lineage section
        lineage_section = ""
        if genome.parent_id:
            lineage_section = f"""## Lineage

- **Parent ID:** {genome.parent_id}
- **Generation:** {genome.generation}"""

        # Footer
        footer = f"""---
*Generated by KIRO2 Template Generator*
*Created: {genome.created_at.isoformat()}*
*Updated: {genome.updated_at.isoformat()}*"""

        # Combine all sections
        sections = [
            frontmatter,
            "",
            f"# {genome.name}",
            "",
            f"**Agent ID:** `{genome.agent_id}`",
            f"**Status:** {genome.status.value}",
            f"**Fitness Score:** {genome.fitness_score:.2f}",
            "",
            capabilities_section,
            "",
            system_prompt_section,
            "",
            config_section,
            "",
            perf_section,
        ]

        if lineage_section:
            sections.extend(["", lineage_section])

        sections.extend(["", footer])

        return "\n".join(sections)

    def _build_capabilities_section(self, genome: AgentGenome) -> str:
        """Yetenekler bolumunu olustur"""
        if not genome.capabilities:
            return "## Capabilities\n\nNo capabilities defined."

        lines = ["## Capabilities", ""]
        for cap in genome.capabilities:
            proficiency_bar = self._proficiency_bar(cap.proficiency)
            lines.append(f"### {cap.name}")
            lines.append(f"- **Type:** {cap.type.value}")
            lines.append(f"- **Proficiency:** {proficiency_bar} ({cap.proficiency:.0%})")
            if cap.description:
                lines.append(f"- **Description:** {cap.description}")
            lines.append("")

        return "\n".join(lines)

    def _proficiency_bar(self, proficiency: float) -> str:
        """Proficiency gorseli olustur"""
        filled = int(proficiency * 10)
        empty = 10 - filled
        return "█" * filled + "░" * empty

    def _get_description(self, genome: AgentGenome) -> str:
        """Agent aciklamasini olustur"""
        if genome.capabilities:
            cap_types = set(c.type.value for c in genome.capabilities)
            return f"Dynamically generated agent with {', '.join(cap_types)} capabilities"
        return "Dynamically generated agent"

    def _sanitize_filename(self, name: str) -> str:
        """Dosya adi icin guvenli string"""
        # Replace spaces and special chars
        safe = name.lower().replace(" ", "-")
        # Remove invalid characters
        safe = "".join(c for c in safe if c.isalnum() or c in "-_")
        return safe

    async def update_settings_json(
        self,
        genome: AgentGenome,
        agent_description: Optional[str] = None
    ) -> GenerationResult:
        """
        settings.json'a yeni agent'i ekle

        Args:
            genome: Agent genome
            agent_description: Aciklama (optional)

        Returns:
            GenerationResult
        """
        try:
            # Load existing settings
            settings = {}
            if self.settings_file.exists():
                with open(self.settings_file, "r", encoding="utf-8") as f:
                    settings = json.load(f)

            # Ensure subagents section exists
            if "subagents" not in settings:
                settings["subagents"] = {"available": []}

            # Add new agent to available list
            agent_name = self._sanitize_filename(genome.name)
            if agent_name not in settings["subagents"]["available"]:
                settings["subagents"]["available"].append(agent_name)

            # Add agent definition to agents section if it doesn't exist
            if "agents" not in settings:
                settings["agents"] = {}

            settings["agents"][agent_name] = {
                "id": genome.agent_id,
                "name": genome.name,
                "model": genome.model.value,
                "tools": genome.tools,
                "description": agent_description or self._get_description(genome),
                "generated": True,
                "generation": genome.generation,
                "fitness_score": genome.fitness_score,
            }

            # Save settings
            with open(self.settings_file, "w", encoding="utf-8") as f:
                json.dump(settings, f, indent=2, ensure_ascii=False)

            return GenerationResult(
                success=True,
                file_path=str(self.settings_file),
            )

        except Exception as e:
            return GenerationResult(
                success=False,
                error=str(e),
            )

    async def remove_agent_from_settings(self, agent_name: str) -> GenerationResult:
        """Agent'i settings'den kaldir"""
        try:
            if not self.settings_file.exists():
                return GenerationResult(
                    success=False,
                    error="Settings file not found",
                )

            with open(self.settings_file, "r", encoding="utf-8") as f:
                settings = json.load(f)

            # Remove from available list
            if "subagents" in settings and "available" in settings["subagents"]:
                safe_name = self._sanitize_filename(agent_name)
                if safe_name in settings["subagents"]["available"]:
                    settings["subagents"]["available"].remove(safe_name)

            # Remove from agents section
            if "agents" in settings and agent_name in settings["agents"]:
                del settings["agents"][agent_name]

            # Save settings
            with open(self.settings_file, "w", encoding="utf-8") as f:
                json.dump(settings, f, indent=2, ensure_ascii=False)

            return GenerationResult(
                success=True,
                file_path=str(self.settings_file),
            )

        except Exception as e:
            return GenerationResult(
                success=False,
                error=str(e),
            )

    async def generate_full_agent(
        self,
        genome: AgentGenome
    ) -> tuple[GenerationResult, GenerationResult]:
        """
        Hem .md hem settings guncelle

        Args:
            genome: Agent genome

        Returns:
            Tuple of (markdown_result, settings_result)
        """
        md_result = await self.generate_agent_markdown(genome)
        settings_result = await self.update_settings_json(genome)

        return md_result, settings_result

    async def batch_generate(
        self,
        genomes: list[AgentGenome]
    ) -> list[tuple[GenerationResult, GenerationResult]]:
        """
        Birden fazla agent icin toplu generasyon

        Args:
            genomes: Agent genome listesi

        Returns:
            List of (markdown_result, settings_result) tuples
        """
        results = []
        for genome in genomes:
            result = await self.generate_full_agent(genome)
            results.append(result)
        return results
