"""add is_anchor

Revision ID: 0045d4670699
Revises: d23f7afe5e9a
Create Date: 2026-08-10 04:53:27.492304

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0045d4670699"
down_revision: Union[str, None] = "d23f7afe5e9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "question_bank",
        sa.Column("is_anchor", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("question_bank", "is_anchor")
    # ### end Alembic commands ###
