"""add virtual currency and daily quest

Revision ID: 0a9560c892c0
Revises: 80601209369e
Create Date: 2026-08-08 14:36:05.736541

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a9560c892c0"
down_revision: Union[str, None] = "80601209369e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "virtual_currency",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="KiroCoin/Zihin Puani vb.",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "virtual_currency")
    # ### end Alembic commands ###
