"""Add cognitive_load_score to osym_linguistic_trends

Revision ID: 28bc3955791b
Revises: b324a922c3b3
Create Date: 2026-08-10 23:20:49.250987

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "28bc3955791b"
down_revision: Union[str, None] = "b324a922c3b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "osym_linguistic_trends",
        sa.Column("cognitive_load_score", sa.Float(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("osym_linguistic_trends", "cognitive_load_score")
    # ### end Alembic commands ###
