"""verify_sync

Revision ID: 3576bbd226d0
Revises: cff60c64b309
Create Date: 2026-08-09 06:12:51.470995

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3576bbd226d0"
down_revision: Union[str, None] = "cff60c64b309"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "kvkk_consents",
        sa.Column(
            "organization_id",
            sa.String(),
            server_default="org_legacy_default",
            nullable=False,
        ),
    )
    op.add_column(
        "kvkk_consents",
        sa.Column("privacy_policy_version", sa.String(length=20), nullable=False),
    )
    op.add_column(
        "kvkk_consents",
        sa.Column(
            "given_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_kvkk_consents_organization_id"),
        "kvkk_consents",
        ["organization_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "kvkk_consents", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "kvkk_consents",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_unique_constraint(None, "streaks", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "streaks", type_="unique")
    op.drop_constraint(None, "kvkk_consents", type_="foreignkey")
    op.drop_constraint(None, "kvkk_consents", type_="foreignkey")
    op.drop_index(op.f("ix_kvkk_consents_organization_id"), table_name="kvkk_consents")
    op.drop_column("kvkk_consents", "given_at")
    op.drop_column("kvkk_consents", "privacy_policy_version")
    op.drop_column("kvkk_consents", "organization_id")
    # ### end Alembic commands ###
