"""add_osym_linguistic_trends

Revision ID: 51b325d6ff41
Revises: 28bc3955791b
Create Date: 2026-08-11 01:57:56.246911

"""

from collections.abc import Sequence
from typing import Union

# revision identifiers, used by Alembic.
revision: str = "51b325d6ff41"
down_revision: Union[str, None] = "28bc3955791b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
