"""check_drift

Revision ID: 80601209369e
Revises: fa067642bdfe
Create Date: 2026-08-07 14:47:44.784614

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "80601209369e"
down_revision: Union[str, None] = "fa067642bdfe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None,
        "api_keys",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None, "api_keys", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "audit_logs", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "audit_logs",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "bkt_states",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None, "class_reports", "users", ["teacher_user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "classrooms",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "classrooms",
        "teacher_profiles",
        ["teacher_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "coaching_events",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "curriculum_alignments",
        "osym_standards",
        ["osym_standard_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "curriculum_alignments",
        "meb_curriculum_standards",
        ["meb_standard_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "daily_quests",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "duel_matches",
        "duel_sessions",
        ["session_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "duel_ratings", "users", ["student_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "duel_ratings",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None, "duel_sessions", "users", ["player2_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None, "duel_sessions", "users", ["player1_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(None, "duels", "topic_hierarchy", ["topic_id"], ["id"])
    op.create_foreign_key(
        None, "dungeon_progress", "topic_hierarchy", ["topic_id"], ["id"]
    )
    op.create_foreign_key(
        None,
        "dungeon_progress",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "eba_content_collections",
        "users",
        ["created_by"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "eba_video_recommendations",
        "eba_videos",
        ["video_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "eba_video_recommendations",
        "student_profiles",
        ["student_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "eba_video_recommendations",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None, "eba_video_usage", "eba_videos", ["video_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "eba_video_usage",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "eba_video_usage",
        "student_profiles",
        ["student_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "eba_videos", "users", ["moderated_by"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "exam_questions", "question_bank", ["question_id"], ["id"]
    )
    op.create_foreign_key(
        None,
        "exam_questions",
        "exam_sessions",
        ["exam_session_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "exam_sessions",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "exam_sessions",
        "student_profiles",
        ["student_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "forum_questions",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None, "fsrs_cards", "users", ["student_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "fsrs_cards",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "fsrs_reviews",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None, "fsrs_reviews", "users", ["student_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "fsrs_reviews", "fsrs_cards", ["card_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "fsrs_schedules",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None, "fsrs_schedules", "users", ["student_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "fsrs_student_profiles",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "fsrs_student_profiles",
        "users",
        ["student_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "fsrs_study_sessions",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None, "fsrs_study_sessions", "users", ["student_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "fsrs_subject_stats", "users", ["student_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "fsrs_subject_stats",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "irt_calibration_history",
        "question_bank",
        ["question_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "kiro2_cat_sessions",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "kiro2_learning_events",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "league_history",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "league_memberships",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "learning_analytics",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "learning_analytics",
        "student_profiles",
        ["student_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "learning_outcomes",
        "meb_curriculum_standards",
        ["meb_standard_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        "idx_lp_student_learning_style",
        "learning_path_student_profiles",
        ["learning_style"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "learning_path_student_profiles",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.alter_column(
        "learning_paths", "organization_id", existing_type=sa.VARCHAR(), nullable=False
    )
    op.create_foreign_key(
        None,
        "learning_paths",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "manipulative_activities",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "manipulative_progress",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "notifications",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "oba_challenge_progress",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "oba_uyeler",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None, "org_memberships", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "org_memberships",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "parent_approvals",
        "users",
        ["student_user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "parent_approvals",
        "users",
        ["parent_user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "parent_child",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "parent_link_codes",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "parent_profiles",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None, "parent_profiles", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "parent_reports", "users", ["parent_user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "parent_reports", "users", ["student_user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "parent_social_settings",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "point_transactions",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "pomodoro_participants",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None, "q_matrix", "nano_skills", ["nano_skill_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "quality_gate_results",
        "quality_gates_runs",
        ["run_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "quality_gates_override_audit",
        "quality_gates_runs",
        ["run_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index(
        "ix_question_embedding_hnsw",
        "question_bank",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_foreign_key(
        None, "question_bank", "users", ["reviewed_by"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "question_bank", "users", ["created_by"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "question_knowledge_mappings",
        "knowledge_points",
        ["knowledge_point_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "question_performance_analytics",
        "question_bank",
        ["question_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "question_tag_associations",
        "question_tags",
        ["tag_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "question_tag_associations",
        "question_bank",
        ["question_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "quiz_questions",
        "question_bank",
        ["question_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "quiz_questions", "quizzes", ["quiz_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "quiz_submissions",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "quiz_submissions",
        "learning_path_student_profiles",
        ["student_id"],
        ["student_id"],
    )
    op.create_foreign_key(
        None,
        "realm_progress",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "refresh_tokens",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None, "refresh_tokens", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "sessions", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "sessions",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "solution_duel_submissions",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "streak_daily_log",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "streaks",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "student_abilities",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_index(
        "idx_student_answer_answered_at",
        "student_answers",
        ["answered_at"],
        unique=False,
    )
    op.create_index(
        "idx_student_answer_incorrect",
        "student_answers",
        ["is_correct"],
        unique=False,
        postgresql_where=sa.text("is_correct = false"),
    )
    op.create_foreign_key(
        None, "student_answers", "question_bank", ["question_id"], ["id"]
    )
    op.create_foreign_key(
        None,
        "student_answers",
        "exam_sessions",
        ["exam_session_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "student_engagement_signals",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "student_goals",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None, "student_grades", "users", ["student_user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "student_grades", "users", ["teacher_user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "student_knowledge_states",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "student_knowledge_states",
        "users",
        ["student_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "student_learning_profiles",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "student_nano_skill_mastery",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "student_nano_skill_mastery",
        "nano_skills",
        ["nano_skill_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "student_nano_skill_mastery",
        "users",
        ["student_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # op.create_index('idx_student_learning_style', 'student_profiles', ['learning_style'], unique=False)
    op.create_foreign_key(
        None,
        "student_profiles",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None, "student_profiles", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "study_plans", "users", ["student_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "study_plans",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "study_sessions",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "study_sessions",
        "learning_path_student_profiles",
        ["student_id"],
        ["student_id"],
    )
    op.create_foreign_key(
        None, "teacher_profiles", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "topic_completions",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "topic_completions",
        "learning_path_student_profiles",
        ["student_id"],
        ["student_id"],
    )
    op.create_foreign_key(
        None,
        "topic_hierarchy",
        "topic_hierarchy",
        ["parent_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "topic_prerequisites", "topic_hierarchy", ["topic_id"], ["id"]
    )
    op.create_foreign_key(
        None, "topic_prerequisites", "topic_hierarchy", ["prereq_id"], ["id"]
    )
    op.create_foreign_key(
        None,
        "topic_progress",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "user_achievements",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "user_badges",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(None, "user_badges", "badges", ["badge_id"], ["id"])
    op.create_foreign_key(
        None, "users", "organizations", ["organization_id"], ["id"], ondelete="RESTRICT"
    )
    op.create_foreign_key(
        None, "weekly_goals", "study_plans", ["plan_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "weekly_progress",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "xp_transactions",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "zpd_history",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "zpd_history", type_="foreignkey")
    op.drop_constraint(None, "xp_transactions", type_="foreignkey")
    op.drop_constraint(None, "weekly_progress", type_="foreignkey")
    op.drop_constraint(None, "weekly_goals", type_="foreignkey")
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_constraint(None, "user_badges", type_="foreignkey")
    op.drop_constraint(None, "user_badges", type_="foreignkey")
    op.drop_constraint(None, "user_achievements", type_="foreignkey")
    op.drop_constraint(None, "topic_progress", type_="foreignkey")
    op.drop_constraint(None, "topic_prerequisites", type_="foreignkey")
    op.drop_constraint(None, "topic_prerequisites", type_="foreignkey")
    op.drop_constraint(None, "topic_hierarchy", type_="foreignkey")
    op.drop_constraint(None, "topic_completions", type_="foreignkey")
    op.drop_constraint(None, "topic_completions", type_="foreignkey")
    op.drop_constraint(None, "teacher_profiles", type_="foreignkey")
    op.drop_constraint(None, "study_sessions", type_="foreignkey")
    op.drop_constraint(None, "study_sessions", type_="foreignkey")
    op.drop_constraint(None, "study_plans", type_="foreignkey")
    op.drop_constraint(None, "study_plans", type_="foreignkey")
    op.drop_constraint(None, "student_profiles", type_="foreignkey")
    op.drop_constraint(None, "student_profiles", type_="foreignkey")
    op.drop_index("idx_student_learning_style", table_name="student_profiles")
    op.drop_constraint(None, "student_nano_skill_mastery", type_="foreignkey")
    op.drop_constraint(None, "student_nano_skill_mastery", type_="foreignkey")
    op.drop_constraint(None, "student_nano_skill_mastery", type_="foreignkey")
    op.drop_constraint(None, "student_learning_profiles", type_="foreignkey")
    op.drop_constraint(None, "student_knowledge_states", type_="foreignkey")
    op.drop_constraint(None, "student_knowledge_states", type_="foreignkey")
    op.drop_constraint(None, "student_grades", type_="foreignkey")
    op.drop_constraint(None, "student_grades", type_="foreignkey")
    op.drop_constraint(None, "student_goals", type_="foreignkey")
    op.drop_constraint(None, "student_engagement_signals", type_="foreignkey")
    op.drop_constraint(None, "student_answers", type_="foreignkey")
    op.drop_constraint(None, "student_answers", type_="foreignkey")
    op.drop_index(
        "idx_student_answer_incorrect",
        table_name="student_answers",
        postgresql_where=sa.text("is_correct = false"),
    )
    op.drop_index("idx_student_answer_answered_at", table_name="student_answers")
    op.drop_constraint(None, "student_abilities", type_="foreignkey")
    op.drop_constraint(None, "streaks", type_="foreignkey")
    op.drop_constraint(None, "streak_daily_log", type_="foreignkey")
    op.drop_constraint(None, "solution_duel_submissions", type_="foreignkey")
    op.drop_constraint(None, "sessions", type_="foreignkey")
    op.drop_constraint(None, "sessions", type_="foreignkey")
    op.drop_constraint(None, "refresh_tokens", type_="foreignkey")
    op.drop_constraint(None, "refresh_tokens", type_="foreignkey")
    op.drop_constraint(None, "realm_progress", type_="foreignkey")
    op.drop_constraint(None, "quiz_submissions", type_="foreignkey")
    op.drop_constraint(None, "quiz_submissions", type_="foreignkey")
    op.drop_constraint(None, "quiz_questions", type_="foreignkey")
    op.drop_constraint(None, "quiz_questions", type_="foreignkey")
    op.drop_constraint(None, "question_tag_associations", type_="foreignkey")
    op.drop_constraint(None, "question_tag_associations", type_="foreignkey")
    op.drop_constraint(None, "question_performance_analytics", type_="foreignkey")
    op.drop_constraint(None, "question_knowledge_mappings", type_="foreignkey")
    op.drop_constraint(None, "question_bank", type_="foreignkey")
    op.drop_constraint(None, "question_bank", type_="foreignkey")
    op.drop_index(
        "ix_question_embedding_hnsw",
        table_name="question_bank",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_constraint(None, "quality_gates_override_audit", type_="foreignkey")
    op.drop_constraint(None, "quality_gate_results", type_="foreignkey")
    op.drop_constraint(None, "q_matrix", type_="foreignkey")
    op.drop_constraint(None, "pomodoro_participants", type_="foreignkey")
    op.drop_constraint(None, "point_transactions", type_="foreignkey")
    op.drop_constraint(None, "parent_social_settings", type_="foreignkey")
    op.drop_constraint(None, "parent_reports", type_="foreignkey")
    op.drop_constraint(None, "parent_reports", type_="foreignkey")
    op.drop_constraint(None, "parent_profiles", type_="foreignkey")
    op.drop_constraint(None, "parent_profiles", type_="foreignkey")
    op.drop_constraint(None, "parent_link_codes", type_="foreignkey")
    op.drop_constraint(None, "parent_child", type_="foreignkey")
    op.drop_constraint(None, "parent_approvals", type_="foreignkey")
    op.drop_constraint(None, "parent_approvals", type_="foreignkey")
    op.drop_constraint(None, "org_memberships", type_="foreignkey")
    op.drop_constraint(None, "org_memberships", type_="foreignkey")
    op.drop_constraint(None, "oba_uyeler", type_="foreignkey")
    op.drop_constraint(None, "oba_challenge_progress", type_="foreignkey")
    op.drop_constraint(None, "notifications", type_="foreignkey")
    op.drop_constraint(None, "manipulative_progress", type_="foreignkey")
    op.drop_constraint(None, "manipulative_activities", type_="foreignkey")
    op.drop_constraint(None, "learning_paths", type_="foreignkey")
    op.alter_column(
        "learning_paths", "organization_id", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_constraint(None, "learning_path_student_profiles", type_="foreignkey")
    op.drop_index(
        "idx_lp_student_learning_style", table_name="learning_path_student_profiles"
    )
    op.drop_constraint(None, "learning_outcomes", type_="foreignkey")
    op.drop_constraint(None, "learning_analytics", type_="foreignkey")
    op.drop_constraint(None, "learning_analytics", type_="foreignkey")
    op.drop_constraint(None, "league_memberships", type_="foreignkey")
    op.drop_constraint(None, "league_history", type_="foreignkey")
    op.drop_constraint(None, "kiro2_learning_events", type_="foreignkey")
    op.drop_constraint(None, "kiro2_cat_sessions", type_="foreignkey")
    op.drop_constraint(None, "irt_calibration_history", type_="foreignkey")
    op.drop_constraint(None, "fsrs_subject_stats", type_="foreignkey")
    op.drop_constraint(None, "fsrs_subject_stats", type_="foreignkey")
    op.drop_constraint(None, "fsrs_study_sessions", type_="foreignkey")
    op.drop_constraint(None, "fsrs_study_sessions", type_="foreignkey")
    op.drop_constraint(None, "fsrs_student_profiles", type_="foreignkey")
    op.drop_constraint(None, "fsrs_student_profiles", type_="foreignkey")
    op.drop_constraint(None, "fsrs_schedules", type_="foreignkey")
    op.drop_constraint(None, "fsrs_schedules", type_="foreignkey")
    op.drop_constraint(None, "fsrs_reviews", type_="foreignkey")
    op.drop_constraint(None, "fsrs_reviews", type_="foreignkey")
    op.drop_constraint(None, "fsrs_reviews", type_="foreignkey")
    op.drop_constraint(None, "fsrs_cards", type_="foreignkey")
    op.drop_constraint(None, "fsrs_cards", type_="foreignkey")
    op.drop_constraint(None, "forum_questions", type_="foreignkey")
    op.drop_constraint(None, "exam_sessions", type_="foreignkey")
    op.drop_constraint(None, "exam_sessions", type_="foreignkey")
    op.drop_constraint(None, "exam_questions", type_="foreignkey")
    op.drop_constraint(None, "exam_questions", type_="foreignkey")
    op.drop_constraint(None, "eba_videos", type_="foreignkey")
    op.drop_constraint(None, "eba_video_usage", type_="foreignkey")
    op.drop_constraint(None, "eba_video_usage", type_="foreignkey")
    op.drop_constraint(None, "eba_video_usage", type_="foreignkey")
    op.drop_constraint(None, "eba_video_recommendations", type_="foreignkey")
    op.drop_constraint(None, "eba_video_recommendations", type_="foreignkey")
    op.drop_constraint(None, "eba_video_recommendations", type_="foreignkey")
    op.drop_constraint(None, "eba_content_collections", type_="foreignkey")
    op.drop_constraint(None, "dungeon_progress", type_="foreignkey")
    op.drop_constraint(None, "dungeon_progress", type_="foreignkey")
    op.drop_constraint(None, "duels", type_="foreignkey")
    op.drop_constraint(None, "duel_sessions", type_="foreignkey")
    op.drop_constraint(None, "duel_sessions", type_="foreignkey")
    op.drop_constraint(None, "duel_ratings", type_="foreignkey")
    op.drop_constraint(None, "duel_ratings", type_="foreignkey")
    op.drop_constraint(None, "duel_matches", type_="foreignkey")
    op.drop_constraint(None, "daily_quests", type_="foreignkey")
    op.drop_constraint(None, "curriculum_alignments", type_="foreignkey")
    op.drop_constraint(None, "curriculum_alignments", type_="foreignkey")
    op.drop_constraint(None, "coaching_events", type_="foreignkey")
    op.drop_constraint(None, "classrooms", type_="foreignkey")
    op.drop_constraint(None, "classrooms", type_="foreignkey")
    op.drop_constraint(None, "class_reports", type_="foreignkey")
    op.drop_constraint(None, "bkt_states", type_="foreignkey")
    op.drop_constraint(None, "audit_logs", type_="foreignkey")
    op.drop_constraint(None, "audit_logs", type_="foreignkey")
    op.drop_constraint(None, "api_keys", type_="foreignkey")
    op.drop_constraint(None, "api_keys", type_="foreignkey")
    # ### end Alembic commands ###
