"""Add neuro_inclusive_mode to learning path profile

Revision ID: b324a922c3b3
Revises: b36e237c943c
Create Date: 2026-08-10 21:18:43.928796

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b324a922c3b3"
down_revision: Union[str, None] = "b36e237c943c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "learning_path_student_profiles",
        sa.Column("neuro_inclusive_mode", sa.Boolean(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("learning_path_student_profiles", "neuro_inclusive_mode")
    # ### end Alembic commands ###
