"""add_osym_linguistic_trends

Revision ID: b36e237c943c
Revises: 0045d4670699
Create Date: 2026-08-10 14:11:09.760680

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b36e237c943c"
down_revision: Union[str, None] = "0045d4670699"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "osym_linguistic_trends",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("exam_type", sa.String(length=50), nullable=False),
        sa.Column("subject", sa.String(length=50), nullable=False),
        sa.Column("avg_word_length", sa.Float(), nullable=False),
        sa.Column("avg_words_per_sentence", sa.Float(), nullable=False),
        sa.Column("atesman_readability_index", sa.Float(), nullable=False),
        sa.Column("question_length_chars", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_osym_linguistic_trends_exam_type"),
        "osym_linguistic_trends",
        ["exam_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_osym_linguistic_trends_id"),
        "osym_linguistic_trends",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_osym_linguistic_trends_subject"),
        "osym_linguistic_trends",
        ["subject"],
        unique=False,
    )
    op.create_index(
        op.f("ix_osym_linguistic_trends_year"),
        "osym_linguistic_trends",
        ["year"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_osym_linguistic_trends_year"), table_name="osym_linguistic_trends"
    )
    op.drop_index(
        op.f("ix_osym_linguistic_trends_subject"), table_name="osym_linguistic_trends"
    )
    op.drop_index(
        op.f("ix_osym_linguistic_trends_id"), table_name="osym_linguistic_trends"
    )
    op.drop_index(
        op.f("ix_osym_linguistic_trends_exam_type"), table_name="osym_linguistic_trends"
    )
    op.drop_table("osym_linguistic_trends")
    # ### end Alembic commands ###
