"""b5_ai_quarantine

Revision ID: c419b81f9698
Revises: 3576bbd226d0
Create Date: 2026-08-09 06:23:36.530019

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c419b81f9698"
down_revision: Union[str, None] = "3576bbd226d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "question_bank",
        sa.Column(
            "is_ai_generated", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "question_bank",
        sa.Column(
            "review_status",
            sa.String(length=20),
            server_default="APPROVED",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("question_bank", "review_status")
    op.drop_column("question_bank", "is_ai_generated")
    # ### end Alembic commands ###
