"""Complete schema documentation

Revision ID: f822e22c28c6
Revises: 60e185cfcca9
Create Date: 2025-10-02 21:55:17.820549

"""

from collections.abc import Sequence
from typing import Union

# revision identifiers, used by Alembic.
revision: str = "f822e22c28c6"
down_revision: Union[str, None] = "60e185cfcca9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
