"""Add unique constraint for student flags

Revision ID: 10f1768d50fc
Revises: fsrs_qid_varchar_20260802
Create Date: 2026-08-03 05:31:34.860493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10f1768d50fc'
down_revision: Union[str, None] = 'fsrs_qid_varchar_20260802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        'uq_student_flags_user_question_type',
        'student_question_flags',
        ['user_id', 'question_id', 'flag_type']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_student_flags_user_question_type', 'student_question_flags', type_='unique')
    # ### end Alembic commands ###
