"""add_cascade_deletes_to_foreign_keys

Revision ID: 4aec28c6c9e0
Revises: db66ce0bd16f
Create Date: 2025-10-04 02:13:40.762639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4aec28c6c9e0"
down_revision: Union[str, None] = "db66ce0bd16f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
