"""unified_schema

Revision ID: 60e185cfcca9
Revises: 
Create Date: 2025-10-02 18:23:58.287634

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "60e185cfcca9"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("test_turkce")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test_turkce",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("metin", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "olusturma_tarihi",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="test_turkce_pkey"),
    )
    # ### end Alembic commands ###
