"""ULTRA_DBA_LENS_HNSW_PGVECTOR

Revision ID: 7b00c895ec27
Revises: 10f1768d50fc
Create Date: 2026-08-03 12:05:07.790328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '7b00c895ec27'
down_revision: Union[str, None] = '10f1768d50fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.create_index(op.f('ix_api_keys_organization_id'), 'api_keys', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_bkt_states_organization_id'), 'bkt_states', ['organization_id'], unique=False)
    op.create_index(op.f('ix_classrooms_is_active'), 'classrooms', ['is_active'], unique=False)
    op.create_index(op.f('ix_classrooms_organization_id'), 'classrooms', ['organization_id'], unique=False)
    op.create_index(op.f('ix_coaching_events_organization_id'), 'coaching_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_daily_quests_organization_id'), 'daily_quests', ['organization_id'], unique=False)
    op.create_index(op.f('ix_duel_ratings_organization_id'), 'duel_ratings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_dungeon_progress_organization_id'), 'dungeon_progress', ['organization_id'], unique=False)
    op.create_index(op.f('ix_eba_content_collections_is_active'), 'eba_content_collections', ['is_active'], unique=False)
    op.create_index(op.f('ix_eba_video_recommendations_organization_id'), 'eba_video_recommendations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_eba_video_usage_organization_id'), 'eba_video_usage', ['organization_id'], unique=False)
    op.create_index(op.f('ix_eba_videos_is_active'), 'eba_videos', ['is_active'], unique=False)
    op.create_index(op.f('ix_educational_contents_is_active'), 'educational_contents', ['is_active'], unique=False)
    op.create_index('idx_exam_question_question', 'exam_questions', ['question_id'], unique=False)
    op.create_index(op.f('ix_exam_sessions_organization_id'), 'exam_sessions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_forum_questions_organization_id'), 'forum_questions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_fsrs_cards_organization_id'), 'fsrs_cards', ['organization_id'], unique=False)
    op.create_index(op.f('ix_fsrs_reviews_organization_id'), 'fsrs_reviews', ['organization_id'], unique=False)
    op.create_index(op.f('ix_fsrs_schedules_organization_id'), 'fsrs_schedules', ['organization_id'], unique=False)
    op.create_index(op.f('ix_fsrs_student_profiles_organization_id'), 'fsrs_student_profiles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_fsrs_study_sessions_organization_id'), 'fsrs_study_sessions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_fsrs_subject_stats_organization_id'), 'fsrs_subject_stats', ['organization_id'], unique=False)
    op.create_index(op.f('ix_kiro2_cat_sessions_organization_id'), 'kiro2_cat_sessions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_kiro2_learning_events_organization_id'), 'kiro2_learning_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_knowledge_points_is_active'), 'knowledge_points', ['is_active'], unique=False)
    op.create_index(op.f('ix_league_history_organization_id'), 'league_history', ['organization_id'], unique=False)
    op.create_index(op.f('ix_league_memberships_organization_id'), 'league_memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_learning_analytics_organization_id'), 'learning_analytics', ['organization_id'], unique=False)
    op.create_index('idx_student_learning_style', 'learning_path_student_profiles', ['learning_style'], unique=False)
    op.create_index(op.f('ix_learning_path_student_profiles_organization_id'), 'learning_path_student_profiles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_learning_paths_organization_id'), 'learning_paths', ['organization_id'], unique=False)
    op.create_index(op.f('ix_manipulative_activities_organization_id'), 'manipulative_activities', ['organization_id'], unique=False)
    op.create_index(op.f('ix_manipulative_progress_organization_id'), 'manipulative_progress', ['organization_id'], unique=False)
    op.create_index(op.f('ix_meb_curriculum_standards_is_active'), 'meb_curriculum_standards', ['is_active'], unique=False)
    op.create_index(op.f('ix_notifications_organization_id'), 'notifications', ['organization_id'], unique=False)
    op.create_index(op.f('ix_oba_challenge_progress_organization_id'), 'oba_challenge_progress', ['organization_id'], unique=False)
    op.create_index(op.f('ix_oba_uyeler_organization_id'), 'oba_uyeler', ['organization_id'], unique=False)
    op.alter_column('org_memberships', 'org_role',
               existing_type=sa.VARCHAR(length=20),
               comment='SCHOOL_ADMIN | TEACHER | STUDENT | PARENT | OBSERVER',
               existing_nullable=False,
               existing_server_default=sa.text("'STUDENT'::character varying"))
    op.create_index(op.f('ix_org_memberships_is_active'), 'org_memberships', ['is_active'], unique=False)
    op.alter_column('organizations', 'org_type',
               existing_type=sa.VARCHAR(length=30),
               comment='dershane | ozel_okul | meb_okul | kurumsal',
               existing_nullable=False,
               existing_server_default=sa.text("'ozel_okul'::character varying"))
    op.alter_column('organizations', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='active | suspended | trial | closed',
               existing_nullable=False,
               existing_server_default=sa.text("'trial'::character varying"))
    op.create_index(op.f('ix_osym_standards_is_active'), 'osym_standards', ['is_active'], unique=False)
    op.create_index(op.f('ix_parent_child_organization_id'), 'parent_child', ['organization_id'], unique=False)
    op.alter_column('parent_link_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_parent_profiles_organization_id'), 'parent_profiles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_parent_social_settings_organization_id'), 'parent_social_settings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_point_transactions_organization_id'), 'point_transactions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_pomodoro_participants_organization_id'), 'pomodoro_participants', ['organization_id'], unique=False)
    op.alter_column('question_bank', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               comment='HNSW indexli Soru Embedding vektörü',
               existing_nullable=True)
    op.create_index('ix_question_embedding_hnsw', 'question_bank', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_quiz_submissions_organization_id'), 'quiz_submissions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_realm_progress_organization_id'), 'realm_progress', ['organization_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_organization_id'), 'refresh_tokens', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sessions_is_active'), 'sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_sessions_organization_id'), 'sessions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_solution_duel_submissions_organization_id'), 'solution_duel_submissions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_streak_daily_log_organization_id'), 'streak_daily_log', ['organization_id'], unique=False)
    op.create_index(op.f('ix_streaks_organization_id'), 'streaks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_student_abilities_organization_id'), 'student_abilities', ['organization_id'], unique=False)
    op.create_index(op.f('ix_student_engagement_signals_organization_id'), 'student_engagement_signals', ['organization_id'], unique=False)
    op.create_index(op.f('ix_student_goals_organization_id'), 'student_goals', ['organization_id'], unique=False)
    op.create_index(op.f('ix_student_knowledge_states_organization_id'), 'student_knowledge_states', ['organization_id'], unique=False)
    op.create_index(op.f('ix_student_learning_profiles_organization_id'), 'student_learning_profiles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_student_nano_skill_mastery_organization_id'), 'student_nano_skill_mastery', ['organization_id'], unique=False)
    op.create_index(op.f('ix_student_profiles_organization_id'), 'student_profiles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_study_plans_is_active'), 'study_plans', ['is_active'], unique=False)
    op.create_index(op.f('ix_study_plans_organization_id'), 'study_plans', ['organization_id'], unique=False)
    op.create_index(op.f('ix_study_sessions_organization_id'), 'study_sessions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_teacher_profiles_organization_id'), 'teacher_profiles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_topic_completions_organization_id'), 'topic_completions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_topic_progress_organization_id'), 'topic_progress', ['organization_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_organization_id'), 'user_achievements', ['organization_id'], unique=False)
    op.create_index(op.f('ix_user_badges_organization_id'), 'user_badges', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_weekly_progress_organization_id'), 'weekly_progress', ['organization_id'], unique=False)
    op.create_index(op.f('ix_xp_transactions_organization_id'), 'xp_transactions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_zpd_history_organization_id'), 'zpd_history', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zpd_history_organization_id'), table_name='zpd_history')
    op.drop_index(op.f('ix_xp_transactions_organization_id'), table_name='xp_transactions')
    op.drop_index(op.f('ix_weekly_progress_organization_id'), table_name='weekly_progress')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_user_badges_organization_id'), table_name='user_badges')
    op.drop_index(op.f('ix_user_achievements_organization_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_topic_progress_organization_id'), table_name='topic_progress')
    op.drop_index(op.f('ix_topic_completions_organization_id'), table_name='topic_completions')
    op.drop_index(op.f('ix_teacher_profiles_organization_id'), table_name='teacher_profiles')
    op.drop_index(op.f('ix_study_sessions_organization_id'), table_name='study_sessions')
    op.drop_index(op.f('ix_study_plans_organization_id'), table_name='study_plans')
    op.drop_index(op.f('ix_study_plans_is_active'), table_name='study_plans')
    op.drop_index(op.f('ix_student_profiles_organization_id'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_nano_skill_mastery_organization_id'), table_name='student_nano_skill_mastery')
    op.drop_index(op.f('ix_student_learning_profiles_organization_id'), table_name='student_learning_profiles')
    op.drop_index(op.f('ix_student_knowledge_states_organization_id'), table_name='student_knowledge_states')
    op.drop_index(op.f('ix_student_goals_organization_id'), table_name='student_goals')
    op.drop_index(op.f('ix_student_engagement_signals_organization_id'), table_name='student_engagement_signals')
    op.drop_index(op.f('ix_student_abilities_organization_id'), table_name='student_abilities')
    op.drop_index(op.f('ix_streaks_organization_id'), table_name='streaks')
    op.drop_index(op.f('ix_streak_daily_log_organization_id'), table_name='streak_daily_log')
    op.drop_index(op.f('ix_solution_duel_submissions_organization_id'), table_name='solution_duel_submissions')
    op.drop_index(op.f('ix_sessions_organization_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_is_active'), table_name='sessions')
    op.drop_index(op.f('ix_refresh_tokens_organization_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_realm_progress_organization_id'), table_name='realm_progress')
    op.drop_index(op.f('ix_quiz_submissions_organization_id'), table_name='quiz_submissions')
    op.drop_index('ix_question_embedding_hnsw', table_name='question_bank', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.alter_column('question_bank', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               comment=None,
               existing_comment='HNSW indexli Soru Embedding vektörü',
               existing_nullable=True)
    op.drop_index(op.f('ix_pomodoro_participants_organization_id'), table_name='pomodoro_participants')
    op.drop_index(op.f('ix_point_transactions_organization_id'), table_name='point_transactions')
    op.drop_index(op.f('ix_parent_social_settings_organization_id'), table_name='parent_social_settings')
    op.drop_index(op.f('ix_parent_profiles_organization_id'), table_name='parent_profiles')
    op.alter_column('parent_link_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_parent_child_organization_id'), table_name='parent_child')
    op.drop_index(op.f('ix_osym_standards_is_active'), table_name='osym_standards')
    op.alter_column('organizations', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='active | suspended | trial | closed',
               existing_nullable=False,
               existing_server_default=sa.text("'trial'::character varying"))
    op.alter_column('organizations', 'org_type',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='dershane | ozel_okul | meb_okul | kurumsal',
               existing_nullable=False,
               existing_server_default=sa.text("'ozel_okul'::character varying"))
    op.drop_index(op.f('ix_org_memberships_is_active'), table_name='org_memberships')
    op.alter_column('org_memberships', 'org_role',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='SCHOOL_ADMIN | TEACHER | STUDENT | PARENT | OBSERVER',
               existing_nullable=False,
               existing_server_default=sa.text("'STUDENT'::character varying"))
    op.drop_index(op.f('ix_oba_uyeler_organization_id'), table_name='oba_uyeler')
    op.drop_index(op.f('ix_oba_challenge_progress_organization_id'), table_name='oba_challenge_progress')
    op.drop_index(op.f('ix_notifications_organization_id'), table_name='notifications')
    op.drop_index(op.f('ix_meb_curriculum_standards_is_active'), table_name='meb_curriculum_standards')
    op.drop_index(op.f('ix_manipulative_progress_organization_id'), table_name='manipulative_progress')
    op.drop_index(op.f('ix_manipulative_activities_organization_id'), table_name='manipulative_activities')
    op.drop_index(op.f('ix_learning_paths_organization_id'), table_name='learning_paths')
    op.drop_index(op.f('ix_learning_path_student_profiles_organization_id'), table_name='learning_path_student_profiles')
    op.drop_index('idx_student_learning_style', table_name='learning_path_student_profiles')
    op.drop_index(op.f('ix_learning_analytics_organization_id'), table_name='learning_analytics')
    op.drop_index(op.f('ix_league_memberships_organization_id'), table_name='league_memberships')
    op.drop_index(op.f('ix_league_history_organization_id'), table_name='league_history')
    op.drop_index(op.f('ix_knowledge_points_is_active'), table_name='knowledge_points')
    op.drop_index(op.f('ix_kiro2_learning_events_organization_id'), table_name='kiro2_learning_events')
    op.drop_index(op.f('ix_kiro2_cat_sessions_organization_id'), table_name='kiro2_cat_sessions')
    op.drop_index(op.f('ix_fsrs_subject_stats_organization_id'), table_name='fsrs_subject_stats')
    op.drop_index(op.f('ix_fsrs_study_sessions_organization_id'), table_name='fsrs_study_sessions')
    op.drop_index(op.f('ix_fsrs_student_profiles_organization_id'), table_name='fsrs_student_profiles')
    op.drop_index(op.f('ix_fsrs_schedules_organization_id'), table_name='fsrs_schedules')
    op.drop_index(op.f('ix_fsrs_reviews_organization_id'), table_name='fsrs_reviews')
    op.drop_index(op.f('ix_fsrs_cards_organization_id'), table_name='fsrs_cards')
    op.drop_index(op.f('ix_forum_questions_organization_id'), table_name='forum_questions')
    op.drop_index(op.f('ix_exam_sessions_organization_id'), table_name='exam_sessions')
    op.drop_index('idx_exam_question_question', table_name='exam_questions')
    op.drop_index(op.f('ix_educational_contents_is_active'), table_name='educational_contents')
    op.drop_index(op.f('ix_eba_videos_is_active'), table_name='eba_videos')
    op.drop_index(op.f('ix_eba_video_usage_organization_id'), table_name='eba_video_usage')
    op.drop_index(op.f('ix_eba_video_recommendations_organization_id'), table_name='eba_video_recommendations')
    op.drop_index(op.f('ix_eba_content_collections_is_active'), table_name='eba_content_collections')
    op.drop_index(op.f('ix_dungeon_progress_organization_id'), table_name='dungeon_progress')
    op.drop_index(op.f('ix_duel_ratings_organization_id'), table_name='duel_ratings')
    op.drop_index(op.f('ix_daily_quests_organization_id'), table_name='daily_quests')
    op.drop_index(op.f('ix_coaching_events_organization_id'), table_name='coaching_events')
    op.drop_index(op.f('ix_classrooms_organization_id'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_is_active'), table_name='classrooms')
    op.drop_index(op.f('ix_bkt_states_organization_id'), table_name='bkt_states')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_api_keys_organization_id'), table_name='api_keys')
    # ### end Alembic commands ###
