"""Initial complete schema with all models

Revision ID: db66ce0bd16f
Revises: f822e22c28c6
Create Date: 2025-10-04 01:03:28.484373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "db66ce0bd16f"
down_revision: Union[str, None] = "f822e22c28c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
