"""create_all_tables

Revision ID: e73a8e0797c1
Revises: 0df6ae499ee4
Create Date: 2026-01-13 08:13:52.766259

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e73a8e0797c1'
down_revision: Union[str, None] = '0df6ae499ee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eba_content_analytics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analysis_date', sa.Date(), nullable=False),
    sa.Column('category', sa.Enum('MATEMATIK', 'TURKCE', 'FEN_BILIMLERI', 'SOSYAL_BILGILER', 'INGILIZCE', 'FIZIK', 'KIMYA', 'BIYOLOJI', 'TARIH', 'COGRAFYA', 'FELSEFE', 'EDEBIYAT', name='ebacontentcategory'), nullable=False),
    sa.Column('grade_level', sa.Enum('SINIF_5', 'SINIF_6', 'SINIF_7', 'SINIF_8', 'SINIF_9', 'SINIF_10', 'SINIF_11', 'SINIF_12', name='ebagradelevel'), nullable=False),
    sa.Column('total_views', sa.Integer(), nullable=False),
    sa.Column('unique_viewers', sa.Integer(), nullable=False),
    sa.Column('total_watch_time_minutes', sa.Integer(), nullable=False),
    sa.Column('average_completion_rate', sa.Float(), nullable=False),
    sa.Column('average_user_rating', sa.Float(), nullable=False),
    sa.Column('total_ratings', sa.Integer(), nullable=False),
    sa.Column('average_learning_effectiveness', sa.Float(), nullable=False),
    sa.Column('trending_score', sa.Float(), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_date', 'category', 'grade_level', name='uq_eba_analytics')
    )
    op.create_index('idx_eba_analytics_category', 'eba_content_analytics', ['category'], unique=False)
    op.create_index('idx_eba_analytics_date', 'eba_content_analytics', ['analysis_date'], unique=False)
    op.create_index('idx_eba_analytics_grade', 'eba_content_analytics', ['grade_level'], unique=False)
    op.create_table('educational_contents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('source_platform', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('source_id', sa.String(length=200), nullable=True),
    sa.Column('subject_area', sa.Enum('MATEMATIK', 'TURKCE', 'FEN', 'SOSYAL', 'FIZIK', 'KIMYA', 'BIYOLOJI', 'INGILIZCE', name='subjectarea'), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('subtopic', sa.String(length=200), nullable=True),
    sa.Column('grade_level', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.Enum('EASY', 'MEDIUM', 'HARD', name='questiondifficulty'), nullable=False),
    sa.Column('educational_score', sa.Float(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('has_subtitles', sa.Boolean(), nullable=False),
    sa.Column('has_transcript', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_content_difficulty', 'educational_contents', ['difficulty_level'], unique=False)
    op.create_index('idx_content_grade', 'educational_contents', ['grade_level'], unique=False)
    op.create_index('idx_content_platform', 'educational_contents', ['source_platform'], unique=False)
    op.create_index('idx_content_score', 'educational_contents', ['educational_score'], unique=False)
    op.create_index('idx_content_subject', 'educational_contents', ['subject_area'], unique=False)
    op.create_index('idx_content_topic', 'educational_contents', ['topic'], unique=False)
    op.create_table('system_configurations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=False),
    sa.Column('config_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_index('idx_config_key', 'system_configurations', ['config_key'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('secret_2fa', sa.String(length=32), nullable=True, comment='TOTP secret key for 2FA'),
    sa.Column('is_2fa_enabled', sa.Boolean(), nullable=False, comment='2FA enabled status'),
    sa.Column('backup_codes_hashed', sa.JSON(), nullable=True, comment='Hashed backup codes for 2FA recovery'),
    sa.Column('is_premium', sa.Boolean(), nullable=False, comment='Premium subscription status'),
    sa.Column('premium_expires_at', sa.DateTime(timezone=True), nullable=True, comment='Premium subscription expiry'),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', 'PARENT', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('last_level_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index('idx_user_role', 'users', ['role'], unique=False)
    op.create_index('idx_user_username', 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('allowed_ips', sa.JSON(), nullable=True),
    sa.Column('rate_limit', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(length=200), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used_ip', sa.String(length=45), nullable=True),
    sa.Column('created_from_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_key_active', 'api_keys', ['is_active'], unique=False)
    op.create_index('idx_api_key_expires', 'api_keys', ['expires_at'], unique=False)
    op.create_index('idx_api_key_hash', 'api_keys', ['key_hash'], unique=False)
    op.create_index('idx_api_key_prefix', 'api_keys', ['key_prefix'], unique=False)
    op.create_index('idx_api_key_revoked', 'api_keys', ['revoked'], unique=False)
    op.create_index('idx_api_key_user', 'api_keys', ['user_id'], unique=False)
    op.create_index(op.f('ix_api_keys_expires_at'), 'api_keys', ['expires_at'], unique=False)
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_api_keys_revoked'), 'api_keys', ['revoked'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_user', 'audit_logs', ['user_id'], unique=False)
    op.create_table('class_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('teacher_user_id', sa.String(), nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=False, comment='12-A, 11-B, etc.'),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('report_period', sa.String(length=50), nullable=False, comment='2025-W47, 2025-Q1, etc.'),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_students', sa.Integer(), nullable=False),
    sa.Column('average_grade', sa.Float(), nullable=False),
    sa.Column('passing_students', sa.Integer(), nullable=False),
    sa.Column('failing_students', sa.Integer(), nullable=False),
    sa.Column('grade_distribution', sa.JSON(), nullable=True, comment='{"90-100": 5, "80-90": 10, ...}'),
    sa.Column('top_students', sa.JSON(), nullable=False),
    sa.Column('struggling_students', sa.JSON(), nullable=False),
    sa.Column('teacher_notes', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_class_report_period', 'class_reports', ['report_period'], unique=False)
    op.create_index('idx_class_report_teacher', 'class_reports', ['teacher_user_id', 'created_at'], unique=False)
    op.create_table('eba_content_collections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('MATEMATIK', 'TURKCE', 'FEN_BILIMLERI', 'SOSYAL_BILGILER', 'INGILIZCE', 'FIZIK', 'KIMYA', 'BIYOLOJI', 'TARIH', 'COGRAFYA', 'FELSEFE', 'EDEBIYAT', name='ebacontentcategory'), nullable=False),
    sa.Column('grade_level', sa.Enum('SINIF_5', 'SINIF_6', 'SINIF_7', 'SINIF_8', 'SINIF_9', 'SINIF_10', 'SINIF_11', 'SINIF_12', name='ebagradelevel'), nullable=False),
    sa.Column('video_ids', sa.JSON(), nullable=True),
    sa.Column('total_videos', sa.Integer(), nullable=False),
    sa.Column('total_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('average_quality_score', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_eba_collection_category', 'eba_content_collections', ['category'], unique=False)
    op.create_index('idx_eba_collection_featured', 'eba_content_collections', ['is_featured'], unique=False)
    op.create_index('idx_eba_collection_grade', 'eba_content_collections', ['grade_level'], unique=False)
    op.create_table('eba_videos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('MATEMATIK', 'TURKCE', 'FEN_BILIMLERI', 'SOSYAL_BILGILER', 'INGILIZCE', 'FIZIK', 'KIMYA', 'BIYOLOJI', 'TARIH', 'COGRAFYA', 'FELSEFE', 'EDEBIYAT', name='ebacontentcategory'), nullable=False),
    sa.Column('grade_level', sa.Enum('SINIF_5', 'SINIF_6', 'SINIF_7', 'SINIF_8', 'SINIF_9', 'SINIF_10', 'SINIF_11', 'SINIF_12', name='ebagradelevel'), nullable=False),
    sa.Column('subject_topics', sa.JSON(), nullable=True),
    sa.Column('difficulty_level', sa.Enum('EASY', 'MEDIUM', 'HARD', name='questiondifficulty'), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('quality_category', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='ebavideoquality'), nullable=False),
    sa.Column('curriculum_alignment', sa.JSON(), nullable=True),
    sa.Column('accessibility_features', sa.JSON(), nullable=True),
    sa.Column('has_subtitles', sa.Boolean(), nullable=False),
    sa.Column('has_transcript', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('share_count', sa.Integer(), nullable=False),
    sa.Column('bookmark_count', sa.Integer(), nullable=False),
    sa.Column('duration_score', sa.Float(), nullable=False),
    sa.Column('title_clarity_score', sa.Float(), nullable=False),
    sa.Column('description_quality_score', sa.Float(), nullable=False),
    sa.Column('curriculum_alignment_score', sa.Float(), nullable=False),
    sa.Column('accessibility_score', sa.Float(), nullable=False),
    sa.Column('moderation_status', sa.String(length=50), nullable=False),
    sa.Column('moderated_by', sa.String(), nullable=True),
    sa.Column('moderation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('moderation_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_minutes >= 1 AND duration_minutes <= 180', name='check_eba_duration'),
    sa.CheckConstraint('quality_score >= 0.0 AND quality_score <= 10.0', name='check_eba_quality_score'),
    sa.ForeignKeyConstraint(['moderated_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_eba_video_category', 'eba_videos', ['category'], unique=False)
    op.create_index('idx_eba_video_created', 'eba_videos', ['created_at'], unique=False)
    op.create_index('idx_eba_video_difficulty', 'eba_videos', ['difficulty_level'], unique=False)
    op.create_index('idx_eba_video_grade', 'eba_videos', ['grade_level'], unique=False)
    op.create_index('idx_eba_video_moderation', 'eba_videos', ['moderation_status'], unique=False)
    op.create_index('idx_eba_video_quality', 'eba_videos', ['quality_score'], unique=False)
    op.create_table('fsrs_cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('front_text', sa.Text(), nullable=False),
    sa.Column('back_text', sa.Text(), nullable=False),
    sa.Column('subject_area', sa.Enum('MATEMATIK', 'TURKCE', 'FEN', 'SOSYAL', 'FIZIK', 'KIMYA', 'BIYOLOJI', 'INGILIZCE', name='subjectarea'), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('stability', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('elapsed_days', sa.Integer(), nullable=False),
    sa.Column('scheduled_days', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_review', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cultural_factors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fsrs_card_due', 'fsrs_cards', ['due_date'], unique=False)
    op.create_index('idx_fsrs_card_state', 'fsrs_cards', ['state'], unique=False)
    op.create_index('idx_fsrs_card_student', 'fsrs_cards', ['student_id'], unique=False)
    op.create_index('idx_fsrs_card_subject', 'fsrs_cards', ['subject_area'], unique=False)
    op.create_table('fsrs_schedules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('schedule_date', sa.Date(), nullable=False),
    sa.Column('total_cards_due', sa.Integer(), nullable=False),
    sa.Column('new_cards', sa.Integer(), nullable=False),
    sa.Column('review_cards', sa.Integer(), nullable=False),
    sa.Column('cards_studied', sa.Integer(), nullable=False),
    sa.Column('study_time_minutes', sa.Integer(), nullable=False),
    sa.Column('retention_rate', sa.Float(), nullable=False),
    sa.Column('cultural_period', sa.String(length=50), nullable=True),
    sa.Column('adjustment_factor', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'schedule_date', name='uq_fsrs_schedule')
    )
    op.create_index('idx_fsrs_schedule_date', 'fsrs_schedules', ['schedule_date'], unique=False)
    op.create_index('idx_fsrs_schedule_student', 'fsrs_schedules', ['student_id'], unique=False)
    op.create_table('fsrs_student_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('fsrs_parameters', sa.JSON(), nullable=False),
    sa.Column('cultural_parameters', sa.JSON(), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('average_retention', sa.Float(), nullable=False),
    sa.Column('study_streak_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_index('idx_fsrs_profile_student', 'fsrs_student_profiles', ['student_id'], unique=False)
    op.create_table('fsrs_study_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('session_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('cards_reviewed', sa.Integer(), nullable=False),
    sa.Column('correct_reviews', sa.Integer(), nullable=False),
    sa.Column('average_response_time', sa.Float(), nullable=False),
    sa.Column('cultural_context', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fsrs_session_date', 'fsrs_study_sessions', ['session_date'], unique=False)
    op.create_index('idx_fsrs_session_student', 'fsrs_study_sessions', ['student_id'], unique=False)
    op.create_table('fsrs_subject_stats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('subject_area', sa.Enum('MATEMATIK', 'TURKCE', 'FEN', 'SOSYAL', 'FIZIK', 'KIMYA', 'BIYOLOJI', 'INGILIZCE', name='subjectarea'), nullable=False),
    sa.Column('total_cards', sa.Integer(), nullable=False),
    sa.Column('mature_cards', sa.Integer(), nullable=False),
    sa.Column('average_stability', sa.Float(), nullable=False),
    sa.Column('average_difficulty', sa.Float(), nullable=False),
    sa.Column('retention_rate', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'subject_area', name='uq_fsrs_subject_stats')
    )
    op.create_index('idx_fsrs_stats_student', 'fsrs_subject_stats', ['student_id'], unique=False)
    op.create_index('idx_fsrs_stats_subject', 'fsrs_subject_stats', ['subject_area'], unique=False)
    op.create_table('manipulative_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('manipulative_type', sa.String(length=50), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_manip_activity_created', 'manipulative_activities', ['created_at'], unique=False)
    op.create_index('idx_manip_activity_user', 'manipulative_activities', ['user_id'], unique=False)
    op.create_index('idx_manip_activity_user_created', 'manipulative_activities', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_manipulative_activities_created_at'), 'manipulative_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_manipulative_activities_id'), 'manipulative_activities', ['id'], unique=False)
    op.create_index(op.f('ix_manipulative_activities_user_id'), 'manipulative_activities', ['user_id'], unique=False)
    op.create_table('manipulative_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('manipulative_type', sa.String(length=50), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=True),
    sa.Column('operation_count', sa.Integer(), nullable=True),
    sa.Column('completion_count', sa.Integer(), nullable=True),
    sa.Column('total_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('avg_duration_seconds', sa.Float(), nullable=True),
    sa.Column('mastery_level', sa.Float(), nullable=True),
    sa.Column('activity_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_manip_progress_type', 'manipulative_progress', ['manipulative_type'], unique=False)
    op.create_index('idx_manip_progress_user', 'manipulative_progress', ['user_id'], unique=False)
    op.create_index('idx_manip_progress_user_type', 'manipulative_progress', ['user_id', 'manipulative_type'], unique=False)
    op.create_index(op.f('ix_manipulative_progress_id'), 'manipulative_progress', ['id'], unique=False)
    op.create_index(op.f('ix_manipulative_progress_user_id'), 'manipulative_progress', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=20), nullable=False),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Higher = more important'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Auto-delete after this date'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('idx_notification_priority', 'notifications', ['user_id', 'priority', 'is_read'], unique=False)
    op.create_index('idx_notification_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('parent_approvals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_user_id', sa.String(), nullable=False),
    sa.Column('parent_user_id', sa.String(), nullable=False),
    sa.Column('request_type', sa.String(length=100), nullable=False, comment='ekstra_ders_izni, sinav_kayit, ozel_egitim'),
    sa.Column('request_description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='beklemede, onaylandi, reddedildi'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parent_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_approval_parent_status', 'parent_approvals', ['parent_user_id', 'status'], unique=False)
    op.create_index('idx_approval_student', 'parent_approvals', ['student_user_id'], unique=False)
    op.create_table('parent_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('children_ids', sa.JSON(), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('sms_notifications', sa.Boolean(), nullable=False),
    sa.Column('weekly_reports', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('parent_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('parent_user_id', sa.String(), nullable=False),
    sa.Column('student_user_id', sa.String(), nullable=False),
    sa.Column('student_name', sa.String(length=200), nullable=False),
    sa.Column('report_period', sa.String(length=50), nullable=False, comment='e.g., 2025-W47'),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_study_minutes', sa.Integer(), nullable=False),
    sa.Column('completed_exams_count', sa.Integer(), nullable=False),
    sa.Column('average_success_rate', sa.Float(), nullable=False, comment='0-100'),
    sa.Column('strong_subjects', sa.JSON(), nullable=False),
    sa.Column('weak_subjects', sa.JSON(), nullable=False),
    sa.Column('weekly_progress_description', sa.Text(), nullable=True),
    sa.Column('parent_recommendations', sa.JSON(), nullable=False),
    sa.Column('support_areas', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_parent_report_parent', 'parent_reports', ['parent_user_id', 'created_at'], unique=False)
    op.create_index('idx_parent_report_period', 'parent_reports', ['report_period'], unique=False)
    op.create_index('idx_parent_report_student', 'parent_reports', ['student_user_id'], unique=False)
    op.create_table('point_transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_transactions_timestamp'), 'point_transactions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_point_transactions_user_id'), 'point_transactions', ['user_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_image_url', sa.String(length=500), nullable=True),
    sa.Column('option_a', sa.Text(), nullable=False),
    sa.Column('option_b', sa.Text(), nullable=False),
    sa.Column('option_c', sa.Text(), nullable=False),
    sa.Column('option_d', sa.Text(), nullable=False),
    sa.Column('option_e', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.String(length=1), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('exam_type', sa.Enum('tyt', 'ayt', 'ydt', 'deneme', name='examtype', native_enum=False), nullable=False),
    sa.Column('subject_area', sa.Enum('matematik', 'turkce', 'fen', 'sosyal', 'fizik', 'kimya', 'biyoloji', 'ingilizce', name='subjectarea', native_enum=False), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('subtopic', sa.String(length=200), nullable=True),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='questiondifficulty', native_enum=False), nullable=False),
    sa.Column('irt_difficulty', sa.Float(), nullable=False),
    sa.Column('irt_discrimination', sa.Float(), nullable=False),
    sa.Column('irt_guessing', sa.Float(), nullable=False),
    sa.Column('morphology_complexity', sa.Float(), nullable=False),
    sa.Column('readability_score', sa.Float(), nullable=False),
    sa.Column('times_asked', sa.Integer(), nullable=False),
    sa.Column('times_correct', sa.Integer(), nullable=False),
    sa.Column('average_response_time', sa.Float(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=False),
    sa.Column('visual_content', sa.JSON(), nullable=True),
    sa.CheckConstraint("correct_answer IN ('A', 'B', 'C', 'D', 'E')", name='check_correct_answer'),
    sa.CheckConstraint('irt_difficulty >= -3.0 AND irt_difficulty <= 3.0', name='check_irt_difficulty'),
    sa.CheckConstraint('irt_discrimination >= 0.1 AND irt_discrimination <= 3.0', name='check_irt_discrimination'),
    sa.CheckConstraint('irt_guessing >= 0.0 AND irt_guessing <= 1.0', name='check_irt_guessing'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_question_difficulty', 'questions', ['difficulty'], unique=False)
    op.create_index('idx_question_exam_type', 'questions', ['exam_type'], unique=False)
    op.create_index('idx_question_irt_difficulty', 'questions', ['irt_difficulty'], unique=False)
    op.create_index('idx_question_subject', 'questions', ['subject_area'], unique=False)
    op.create_index('idx_question_topic', 'questions', ['topic'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('device_name', sa.String(length=200), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(length=200), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_refresh_token_expires', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('idx_refresh_token_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index('idx_refresh_token_jti', 'refresh_tokens', ['jti'], unique=False)
    op.create_index('idx_refresh_token_revoked', 'refresh_tokens', ['revoked'], unique=False)
    op.create_index('idx_refresh_token_user', 'refresh_tokens', ['user_id'], unique=False)
    op.create_index('idx_refresh_token_user_device', 'refresh_tokens', ['user_id', 'device_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_revoked'), 'refresh_tokens', ['revoked'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('device_info', sa.JSON(), nullable=True, comment='Device/browser info'),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_active', 'sessions', ['is_active', 'expires_at'], unique=False)
    op.create_index('idx_session_expires_at', 'sessions', ['expires_at'], unique=False)
    op.create_index('idx_session_user_id', 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_sessions_token'), 'sessions', ['token'], unique=True)
    op.create_table('student_goals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goal_type', sa.String(length=20), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_goal_end_date', 'student_goals', ['end_date'], unique=False)
    op.create_index('idx_goal_user_status', 'student_goals', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_student_goals_id'), 'student_goals', ['id'], unique=False)
    op.create_index(op.f('ix_student_goals_user_id'), 'student_goals', ['user_id'], unique=False)
    op.create_table('student_grades',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('teacher_user_id', sa.String(), nullable=False),
    sa.Column('student_user_id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False, comment='Matematik, Türkçe, etc.'),
    sa.Column('grade_type', sa.String(length=50), nullable=False, comment='yazili, sözlü, proje, performans'),
    sa.Column('grade_value', sa.Float(), nullable=False, comment='0-100 or other scale'),
    sa.Column('max_grade', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False, comment='Weight in final grade calculation'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('graded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False, comment='2024-2025'),
    sa.Column('semester', sa.Integer(), nullable=False, comment='1 or 2'),
    sa.ForeignKeyConstraint(['student_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_grade_academic_year', 'student_grades', ['academic_year', 'semester'], unique=False)
    op.create_index('idx_grade_student_subject', 'student_grades', ['student_user_id', 'subject'], unique=False)
    op.create_index('idx_grade_teacher', 'student_grades', ['teacher_user_id'], unique=False)
    op.create_table('student_learning_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('vark_visual', sa.Float(), nullable=False),
    sa.Column('vark_auditory', sa.Float(), nullable=False),
    sa.Column('vark_reading', sa.Float(), nullable=False),
    sa.Column('vark_kinesthetic', sa.Float(), nullable=False),
    sa.Column('felder_active_reflective', sa.Float(), nullable=False),
    sa.Column('felder_sensing_intuitive', sa.Float(), nullable=False),
    sa.Column('felder_visual_verbal', sa.Float(), nullable=False),
    sa.Column('felder_sequential_global', sa.Float(), nullable=False),
    sa.Column('hybrid_code', sa.String(length=20), nullable=False),
    sa.Column('dominant_vark_style', sa.String(length=20), nullable=False),
    sa.Column('dominant_felder_dimension', sa.String(length=30), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('profile_description', sa.Text(), nullable=True),
    sa.Column('behavioral_data_snapshot', sa.JSON(), nullable=True),
    sa.Column('questionnaire_responses', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_learning_profiles_hybrid_code'), 'student_learning_profiles', ['hybrid_code'], unique=False)
    op.create_index(op.f('ix_student_learning_profiles_id'), 'student_learning_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_student_learning_profiles_student_id'), 'student_learning_profiles', ['student_id'], unique=True)
    op.create_table('student_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('grade_level', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(length=200), nullable=True),
    sa.Column('target_university', sa.String(length=200), nullable=True),
    sa.Column('target_department', sa.String(length=200), nullable=True),
    sa.Column('hedef_sinav', sa.String(length=20), nullable=True),
    sa.Column('veli_onay', sa.Boolean(), nullable=False),
    sa.Column('learning_style', sa.Enum('VISUAL', 'AUDITORY', 'KINESTHETIC', 'READING_WRITING', name='learningstyle'), nullable=True),
    sa.Column('study_hours_per_day', sa.Integer(), nullable=True),
    sa.Column('preferred_study_time', sa.String(length=50), nullable=True),
    sa.Column('current_level', sa.Float(), nullable=False),
    sa.Column('total_study_hours', sa.Integer(), nullable=False),
    sa.Column('total_questions_solved', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('vark_profile', sa.JSON(), nullable=True),
    sa.Column('zpd_range', sa.JSON(), nullable=True),
    sa.Column('irt_ability', sa.Float(), nullable=False),
    sa.Column('fsrs_parameters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('current_level >= 0.0 AND current_level <= 10.0', name='check_current_level'),
    sa.CheckConstraint('grade_level >= 9 AND grade_level <= 12', name='check_grade_level'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_student_grade_level', 'student_profiles', ['grade_level'], unique=False)
    op.create_index('idx_student_grade_style', 'student_profiles', ['grade_level', 'learning_style'], unique=False)
    op.create_index('idx_student_learning_style', 'student_profiles', ['learning_style'], unique=False)
    op.create_index('idx_student_user_grade', 'student_profiles', ['user_id', 'grade_level'], unique=False)
    op.create_table('teacher_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('school_name', sa.String(length=200), nullable=False),
    sa.Column('subject_areas', sa.JSON(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('education_level', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_achievements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('achievement_id', sa.String(length=100), nullable=False),
    sa.Column('achievement_type', sa.String(length=50), nullable=False),
    sa.Column('achievement_name', sa.String(length=200), nullable=False),
    sa.Column('achievement_description', sa.Text(), nullable=True),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_target', sa.Integer(), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('reward_xp', sa.Integer(), nullable=True),
    sa.Column('reward_points', sa.Integer(), nullable=True),
    sa.Column('reward_badge_id', sa.String(length=100), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_achievements_achievement_id'), 'user_achievements', ['achievement_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.create_table('user_badges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('badge_id', sa.String(length=100), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=False),
    sa.Column('auto_awarded', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_badges_badge_id'), 'user_badges', ['badge_id'], unique=False)
    op.create_index(op.f('ix_user_badges_user_id'), 'user_badges', ['user_id'], unique=False)
    op.create_table('weekly_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('total_activities', sa.Integer(), nullable=True),
    sa.Column('total_time_seconds', sa.Integer(), nullable=True),
    sa.Column('streak_days', sa.Integer(), nullable=True),
    sa.Column('daily_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'year', 'week_number', name='uq_weekly_progress')
    )
    op.create_index('idx_weekly_progress_user', 'weekly_progress', ['user_id'], unique=False)
    op.create_index('idx_weekly_progress_year_week', 'weekly_progress', ['year', 'week_number'], unique=False)
    op.create_index(op.f('ix_weekly_progress_id'), 'weekly_progress', ['id'], unique=False)
    op.create_index(op.f('ix_weekly_progress_user_id'), 'weekly_progress', ['user_id'], unique=False)
    op.create_table('classrooms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('teacher_id', sa.String(), nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=False),
    sa.Column('grade_level', sa.Integer(), nullable=False),
    sa.Column('subject_area', sa.Enum('MATEMATIK', 'TURKCE', 'FEN', 'SOSYAL', 'FIZIK', 'KIMYA', 'BIYOLOJI', 'INGILIZCE', name='subjectarea'), nullable=False),
    sa.Column('school_year', sa.String(length=20), nullable=False),
    sa.Column('student_ids', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_students', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('grade_level >= 9 AND grade_level <= 12', name='check_class_grade_level'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_classroom_grade', 'classrooms', ['grade_level'], unique=False)
    op.create_index('idx_classroom_subject', 'classrooms', ['subject_area'], unique=False)
    op.create_index('idx_classroom_teacher', 'classrooms', ['teacher_id'], unique=False)
    op.create_table('eba_video_recommendations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('recommendation_score', sa.Float(), nullable=False),
    sa.Column('recommendation_reason', sa.String(length=200), nullable=False),
    sa.Column('recommendation_category', sa.String(length=100), nullable=False),
    sa.Column('learning_style_match', sa.Float(), nullable=False),
    sa.Column('difficulty_appropriateness', sa.Float(), nullable=False),
    sa.Column('curriculum_relevance', sa.Float(), nullable=False),
    sa.Column('shown_to_student', sa.Boolean(), nullable=False),
    sa.Column('clicked_by_student', sa.Boolean(), nullable=False),
    sa.Column('watched_by_student', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('shown_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('recommendation_score >= 0.0 AND recommendation_score <= 10.0', name='check_eba_rec_score'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['eba_videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_eba_rec_created', 'eba_video_recommendations', ['created_at'], unique=False)
    op.create_index('idx_eba_rec_score', 'eba_video_recommendations', ['recommendation_score'], unique=False)
    op.create_index('idx_eba_rec_student', 'eba_video_recommendations', ['student_id'], unique=False)
    op.create_index('idx_eba_rec_video', 'eba_video_recommendations', ['video_id'], unique=False)
    op.create_table('eba_video_usage',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('watch_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('completion_percentage', sa.Float(), nullable=False),
    sa.Column('paused_count', sa.Integer(), nullable=False),
    sa.Column('rewound_count', sa.Integer(), nullable=False),
    sa.Column('fast_forwarded_count', sa.Integer(), nullable=False),
    sa.Column('user_rating', sa.Float(), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('pre_knowledge_score', sa.Float(), nullable=True),
    sa.Column('post_knowledge_score', sa.Float(), nullable=True),
    sa.Column('learning_effectiveness', sa.Float(), nullable=True),
    sa.CheckConstraint('completion_percentage >= 0.0 AND completion_percentage <= 100.0', name='check_eba_completion'),
    sa.CheckConstraint('user_rating IS NULL OR (user_rating >= 1.0 AND user_rating <= 5.0)', name='check_eba_rating'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['eba_videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'student_id', 'started_at', name='uq_eba_video_usage')
    )
    op.create_index('idx_eba_usage_started', 'eba_video_usage', ['started_at'], unique=False)
    op.create_index('idx_eba_usage_student', 'eba_video_usage', ['student_id'], unique=False)
    op.create_index('idx_eba_usage_video', 'eba_video_usage', ['video_id'], unique=False)
    op.create_table('exam_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('exam_type', sa.Enum('TYT', 'AYT', 'YDT', 'DENEME', name='examtype'), nullable=False),
    sa.Column('exam_name', sa.String(length=200), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_question_index', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('total_correct', sa.Integer(), nullable=False),
    sa.Column('total_wrong', sa.Integer(), nullable=False),
    sa.Column('total_empty', sa.Integer(), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('scaled_score', sa.Float(), nullable=True),
    sa.Column('percentile', sa.Float(), nullable=True),
    sa.Column('estimated_ability', sa.Float(), nullable=False),
    sa.Column('ability_confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exam_session_created', 'exam_sessions', ['created_at'], unique=False)
    op.create_index('idx_exam_session_status', 'exam_sessions', ['status'], unique=False)
    op.create_index('idx_exam_session_student', 'exam_sessions', ['student_id'], unique=False)
    op.create_index('idx_exam_session_type', 'exam_sessions', ['exam_type'], unique=False)
    op.create_table('fsrs_reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('review_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('response_time_seconds', sa.Float(), nullable=False),
    sa.Column('old_stability', sa.Float(), nullable=False),
    sa.Column('new_stability', sa.Float(), nullable=False),
    sa.Column('old_difficulty', sa.Float(), nullable=False),
    sa.Column('new_difficulty', sa.Float(), nullable=False),
    sa.Column('cultural_adjustment', sa.Float(), nullable=False),
    sa.CheckConstraint('grade >= 1 AND grade <= 4', name='check_fsrs_grade'),
    sa.ForeignKeyConstraint(['card_id'], ['fsrs_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fsrs_review_card', 'fsrs_reviews', ['card_id'], unique=False)
    op.create_index('idx_fsrs_review_date', 'fsrs_reviews', ['review_date'], unique=False)
    op.create_index('idx_fsrs_review_student', 'fsrs_reviews', ['student_id'], unique=False)
    op.create_table('learning_analytics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('subject_area', sa.Enum('MATEMATIK', 'TURKCE', 'FEN', 'SOSYAL', 'FIZIK', 'KIMYA', 'BIYOLOJI', 'INGILIZCE', name='subjectarea'), nullable=False),
    sa.Column('questions_attempted', sa.Integer(), nullable=False),
    sa.Column('questions_correct', sa.Integer(), nullable=False),
    sa.Column('average_response_time', sa.Float(), nullable=False),
    sa.Column('study_time_minutes', sa.Integer(), nullable=False),
    sa.Column('skill_level', sa.Float(), nullable=False),
    sa.Column('improvement_rate', sa.Float(), nullable=False),
    sa.Column('difficulty_preference', sa.Float(), nullable=False),
    sa.Column('zpd_utilization', sa.Float(), nullable=False),
    sa.Column('fsrs_retention_rate', sa.Float(), nullable=False),
    sa.Column('morphology_awareness', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'date', 'subject_area', name='uq_learning_analytics')
    )
    op.create_index('idx_learning_analytics_date', 'learning_analytics', ['date'], unique=False)
    op.create_index('idx_learning_analytics_student', 'learning_analytics', ['student_id'], unique=False)
    op.create_index('idx_learning_analytics_subject', 'learning_analytics', ['subject_area'], unique=False)
    op.create_table('exam_questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('exam_session_id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_session_id'], ['exam_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_session_id', 'question_order', name='uq_exam_question_order')
    )
    op.create_index('idx_exam_question_order', 'exam_questions', ['question_order'], unique=False)
    op.create_index('idx_exam_question_session', 'exam_questions', ['exam_session_id'], unique=False)
    op.create_table('student_answers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('exam_session_id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('selected_answer', sa.String(length=1), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('response_time_seconds', sa.Float(), nullable=False),
    sa.Column('answer_changes', sa.Integer(), nullable=False),
    sa.Column('time_to_first_answer', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("selected_answer IS NULL OR selected_answer IN ('A', 'B', 'C', 'D', 'E')", name='check_selected_answer'),
    sa.ForeignKeyConstraint(['exam_session_id'], ['exam_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_session_id', 'question_id', name='uq_student_answer')
    )
    op.create_index('idx_student_answer_question', 'student_answers', ['question_id'], unique=False)
    op.create_index('idx_student_answer_session', 'student_answers', ['exam_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_student_answer_session', table_name='student_answers')
    op.drop_index('idx_student_answer_question', table_name='student_answers')
    op.drop_table('student_answers')
    op.drop_index('idx_exam_question_session', table_name='exam_questions')
    op.drop_index('idx_exam_question_order', table_name='exam_questions')
    op.drop_table('exam_questions')
    op.drop_index('idx_learning_analytics_subject', table_name='learning_analytics')
    op.drop_index('idx_learning_analytics_student', table_name='learning_analytics')
    op.drop_index('idx_learning_analytics_date', table_name='learning_analytics')
    op.drop_table('learning_analytics')
    op.drop_index('idx_fsrs_review_student', table_name='fsrs_reviews')
    op.drop_index('idx_fsrs_review_date', table_name='fsrs_reviews')
    op.drop_index('idx_fsrs_review_card', table_name='fsrs_reviews')
    op.drop_table('fsrs_reviews')
    op.drop_index('idx_exam_session_type', table_name='exam_sessions')
    op.drop_index('idx_exam_session_student', table_name='exam_sessions')
    op.drop_index('idx_exam_session_status', table_name='exam_sessions')
    op.drop_index('idx_exam_session_created', table_name='exam_sessions')
    op.drop_table('exam_sessions')
    op.drop_index('idx_eba_usage_video', table_name='eba_video_usage')
    op.drop_index('idx_eba_usage_student', table_name='eba_video_usage')
    op.drop_index('idx_eba_usage_started', table_name='eba_video_usage')
    op.drop_table('eba_video_usage')
    op.drop_index('idx_eba_rec_video', table_name='eba_video_recommendations')
    op.drop_index('idx_eba_rec_student', table_name='eba_video_recommendations')
    op.drop_index('idx_eba_rec_score', table_name='eba_video_recommendations')
    op.drop_index('idx_eba_rec_created', table_name='eba_video_recommendations')
    op.drop_table('eba_video_recommendations')
    op.drop_index('idx_classroom_teacher', table_name='classrooms')
    op.drop_index('idx_classroom_subject', table_name='classrooms')
    op.drop_index('idx_classroom_grade', table_name='classrooms')
    op.drop_table('classrooms')
    op.drop_index(op.f('ix_weekly_progress_user_id'), table_name='weekly_progress')
    op.drop_index(op.f('ix_weekly_progress_id'), table_name='weekly_progress')
    op.drop_index('idx_weekly_progress_year_week', table_name='weekly_progress')
    op.drop_index('idx_weekly_progress_user', table_name='weekly_progress')
    op.drop_table('weekly_progress')
    op.drop_index(op.f('ix_user_badges_user_id'), table_name='user_badges')
    op.drop_index(op.f('ix_user_badges_badge_id'), table_name='user_badges')
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_achievement_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_table('teacher_profiles')
    op.drop_index('idx_student_user_grade', table_name='student_profiles')
    op.drop_index('idx_student_learning_style', table_name='student_profiles')
    op.drop_index('idx_student_grade_style', table_name='student_profiles')
    op.drop_index('idx_student_grade_level', table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_index(op.f('ix_student_learning_profiles_student_id'), table_name='student_learning_profiles')
    op.drop_index(op.f('ix_student_learning_profiles_id'), table_name='student_learning_profiles')
    op.drop_index(op.f('ix_student_learning_profiles_hybrid_code'), table_name='student_learning_profiles')
    op.drop_table('student_learning_profiles')
    op.drop_index('idx_grade_teacher', table_name='student_grades')
    op.drop_index('idx_grade_student_subject', table_name='student_grades')
    op.drop_index('idx_grade_academic_year', table_name='student_grades')
    op.drop_table('student_grades')
    op.drop_index(op.f('ix_student_goals_user_id'), table_name='student_goals')
    op.drop_index(op.f('ix_student_goals_id'), table_name='student_goals')
    op.drop_index('idx_goal_user_status', table_name='student_goals')
    op.drop_index('idx_goal_end_date', table_name='student_goals')
    op.drop_table('student_goals')
    op.drop_index(op.f('ix_sessions_token'), table_name='sessions')
    op.drop_index('idx_session_user_id', table_name='sessions')
    op.drop_index('idx_session_expires_at', table_name='sessions')
    op.drop_index('idx_session_active', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_revoked'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_index('idx_refresh_token_user_device', table_name='refresh_tokens')
    op.drop_index('idx_refresh_token_user', table_name='refresh_tokens')
    op.drop_index('idx_refresh_token_revoked', table_name='refresh_tokens')
    op.drop_index('idx_refresh_token_jti', table_name='refresh_tokens')
    op.drop_index('idx_refresh_token_hash', table_name='refresh_tokens')
    op.drop_index('idx_refresh_token_expires', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_question_topic', table_name='questions')
    op.drop_index('idx_question_subject', table_name='questions')
    op.drop_index('idx_question_irt_difficulty', table_name='questions')
    op.drop_index('idx_question_exam_type', table_name='questions')
    op.drop_index('idx_question_difficulty', table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_point_transactions_user_id'), table_name='point_transactions')
    op.drop_index(op.f('ix_point_transactions_timestamp'), table_name='point_transactions')
    op.drop_table('point_transactions')
    op.drop_index('idx_parent_report_student', table_name='parent_reports')
    op.drop_index('idx_parent_report_period', table_name='parent_reports')
    op.drop_index('idx_parent_report_parent', table_name='parent_reports')
    op.drop_table('parent_reports')
    op.drop_table('parent_profiles')
    op.drop_index('idx_approval_student', table_name='parent_approvals')
    op.drop_index('idx_approval_parent_status', table_name='parent_approvals')
    op.drop_table('parent_approvals')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index('idx_notification_user_read', table_name='notifications')
    op.drop_index('idx_notification_priority', table_name='notifications')
    op.drop_index('idx_notification_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_manipulative_progress_user_id'), table_name='manipulative_progress')
    op.drop_index(op.f('ix_manipulative_progress_id'), table_name='manipulative_progress')
    op.drop_index('idx_manip_progress_user_type', table_name='manipulative_progress')
    op.drop_index('idx_manip_progress_user', table_name='manipulative_progress')
    op.drop_index('idx_manip_progress_type', table_name='manipulative_progress')
    op.drop_table('manipulative_progress')
    op.drop_index(op.f('ix_manipulative_activities_user_id'), table_name='manipulative_activities')
    op.drop_index(op.f('ix_manipulative_activities_id'), table_name='manipulative_activities')
    op.drop_index(op.f('ix_manipulative_activities_created_at'), table_name='manipulative_activities')
    op.drop_index('idx_manip_activity_user_created', table_name='manipulative_activities')
    op.drop_index('idx_manip_activity_user', table_name='manipulative_activities')
    op.drop_index('idx_manip_activity_created', table_name='manipulative_activities')
    op.drop_table('manipulative_activities')
    op.drop_index('idx_fsrs_stats_subject', table_name='fsrs_subject_stats')
    op.drop_index('idx_fsrs_stats_student', table_name='fsrs_subject_stats')
    op.drop_table('fsrs_subject_stats')
    op.drop_index('idx_fsrs_session_student', table_name='fsrs_study_sessions')
    op.drop_index('idx_fsrs_session_date', table_name='fsrs_study_sessions')
    op.drop_table('fsrs_study_sessions')
    op.drop_index('idx_fsrs_profile_student', table_name='fsrs_student_profiles')
    op.drop_table('fsrs_student_profiles')
    op.drop_index('idx_fsrs_schedule_student', table_name='fsrs_schedules')
    op.drop_index('idx_fsrs_schedule_date', table_name='fsrs_schedules')
    op.drop_table('fsrs_schedules')
    op.drop_index('idx_fsrs_card_subject', table_name='fsrs_cards')
    op.drop_index('idx_fsrs_card_student', table_name='fsrs_cards')
    op.drop_index('idx_fsrs_card_state', table_name='fsrs_cards')
    op.drop_index('idx_fsrs_card_due', table_name='fsrs_cards')
    op.drop_table('fsrs_cards')
    op.drop_index('idx_eba_video_quality', table_name='eba_videos')
    op.drop_index('idx_eba_video_moderation', table_name='eba_videos')
    op.drop_index('idx_eba_video_grade', table_name='eba_videos')
    op.drop_index('idx_eba_video_difficulty', table_name='eba_videos')
    op.drop_index('idx_eba_video_created', table_name='eba_videos')
    op.drop_index('idx_eba_video_category', table_name='eba_videos')
    op.drop_table('eba_videos')
    op.drop_index('idx_eba_collection_grade', table_name='eba_content_collections')
    op.drop_index('idx_eba_collection_featured', table_name='eba_content_collections')
    op.drop_index('idx_eba_collection_category', table_name='eba_content_collections')
    op.drop_table('eba_content_collections')
    op.drop_index('idx_class_report_teacher', table_name='class_reports')
    op.drop_index('idx_class_report_period', table_name='class_reports')
    op.drop_table('class_reports')
    op.drop_index('idx_audit_user', table_name='audit_logs')
    op.drop_index('idx_audit_resource', table_name='audit_logs')
    op.drop_index('idx_audit_created', table_name='audit_logs')
    op.drop_index('idx_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_revoked'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_expires_at'), table_name='api_keys')
    op.drop_index('idx_api_key_user', table_name='api_keys')
    op.drop_index('idx_api_key_revoked', table_name='api_keys')
    op.drop_index('idx_api_key_prefix', table_name='api_keys')
    op.drop_index('idx_api_key_hash', table_name='api_keys')
    op.drop_index('idx_api_key_expires', table_name='api_keys')
    op.drop_index('idx_api_key_active', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_username', table_name='users')
    op.drop_index('idx_user_role', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_index('idx_user_created_at', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_config_key', table_name='system_configurations')
    op.drop_table('system_configurations')
    op.drop_index('idx_content_topic', table_name='educational_contents')
    op.drop_index('idx_content_subject', table_name='educational_contents')
    op.drop_index('idx_content_score', table_name='educational_contents')
    op.drop_index('idx_content_platform', table_name='educational_contents')
    op.drop_index('idx_content_grade', table_name='educational_contents')
    op.drop_index('idx_content_difficulty', table_name='educational_contents')
    op.drop_table('educational_contents')
    op.drop_index('idx_eba_analytics_grade', table_name='eba_content_analytics')
    op.drop_index('idx_eba_analytics_date', table_name='eba_content_analytics')
    op.drop_index('idx_eba_analytics_category', table_name='eba_content_analytics')
    op.drop_table('eba_content_analytics')
    # ### end Alembic commands ###
