"""
HTML Reporter
=============

Visual HTML report with charts and drill-down details.
Uses embedded CSS and Chart.js for visualization.
"""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

from ..models import GateStatus, PipelineResult


class HtmlReporter:
    """
    HTML reporter for quality gate results.

    Features:
    - Visual status dashboard
    - Score charts (Chart.js)
    - Issue drill-down
    - Trend visualization (if historical data provided)
    """

    STATUS_COLORS = {
        GateStatus.PASS: "#22c55e",      # Green
        GateStatus.WARNING: "#eab308",    # Yellow
        GateStatus.FAIL: "#ef4444",       # Red
        GateStatus.SKIPPED: "#9ca3af",    # Gray
        GateStatus.TIMEOUT: "#f97316",    # Orange
        GateStatus.ERROR: "#dc2626",      # Dark red
    }

    def __init__(
        self,
        output_path: Path | None = None,
        title: str = "Quality Gates Report",
        include_charts: bool = True,
    ):
        """
        Initialize HTML reporter.

        Args:
            output_path: Path to write HTML file
            title: Report title
            include_charts: Include Chart.js visualizations
        """
        self.output_path = output_path
        self.title = title
        self.include_charts = include_charts

    def report(self, result: PipelineResult) -> str:
        """
        Generate HTML report.

        Args:
            result: Pipeline result to report

        Returns:
            HTML string
        """
        html = self._generate_html(result)

        if self.output_path:
            self.output_path.parent.mkdir(parents=True, exist_ok=True)
            self.output_path.write_text(html, encoding="utf-8")

        return html

    def _generate_html(self, result: PipelineResult) -> str:
        """Generate complete HTML document."""
        status_color = self.STATUS_COLORS.get(result.status, "#6b7280")

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{self.title}</title>
    {self._get_styles()}
    {self._get_chart_script() if self.include_charts else ""}
</head>
<body>
    <div class="container">
        <header class="header">
            <h1>{self.title}</h1>
            <div class="status-badge" style="background-color: {status_color}">
                {result.status.value.upper()}
            </div>
        </header>

        <div class="summary-cards">
            <div class="card">
                <div class="card-title">Total Score</div>
                <div class="card-value">{result.total_score:.1f}/10</div>
            </div>
            <div class="card">
                <div class="card-title">Passed</div>
                <div class="card-value" style="color: #22c55e">{result.passed_gates}</div>
            </div>
            <div class="card">
                <div class="card-title">Failed</div>
                <div class="card-value" style="color: #ef4444">{result.failed_gates}</div>
            </div>
            <div class="card">
                <div class="card-title">Duration</div>
                <div class="card-value">{result.total_execution_time_ms:.0f}ms</div>
            </div>
        </div>

        <div class="context">
            <span><strong>Branch:</strong> {result.branch or 'N/A'}</span>
            <span><strong>Commit:</strong> {result.commit_hash[:8] if result.commit_hash else 'N/A'}</span>
            <span><strong>Time:</strong> {result.completed_at.strftime('%Y-%m-%d %H:%M:%S') if result.completed_at else 'N/A'}</span>
        </div>

        {self._get_chart_section(result) if self.include_charts else ""}

        <section class="gates-section">
            <h2>Gate Results</h2>
            <div class="gates-grid">
                {self._generate_gate_cards(result)}
            </div>
        </section>

        <section class="issues-section">
            <h2>Issues</h2>
            {self._generate_issues_table(result)}
        </section>

        <footer class="footer">
            <p>Generated by KIRO2 Quality Gates Pipeline</p>
            <p>{datetime.now(UTC).strftime('%Y-%m-%d %H:%M:%S UTC')}</p>
        </footer>
    </div>

    {self._get_chart_init(result) if self.include_charts else ""}
</body>
</html>"""

    def _get_styles(self) -> str:
        """Get embedded CSS styles."""
        return """
<style>
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }

    body {
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
        background-color: #f3f4f6;
        color: #1f2937;
        line-height: 1.6;
    }

    .container {
        max-width: 1200px;
        margin: 0 auto;
        padding: 2rem;
    }

    .header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 2rem;
    }

    .header h1 {
        font-size: 1.875rem;
        font-weight: 700;
    }

    .status-badge {
        padding: 0.5rem 1rem;
        border-radius: 0.5rem;
        color: white;
        font-weight: 600;
        font-size: 0.875rem;
    }

    .summary-cards {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
        gap: 1rem;
        margin-bottom: 2rem;
    }

    .card {
        background: white;
        padding: 1.5rem;
        border-radius: 0.5rem;
        box-shadow: 0 1px 3px rgba(0,0,0,0.1);
        text-align: center;
    }

    .card-title {
        font-size: 0.875rem;
        color: #6b7280;
        margin-bottom: 0.5rem;
    }

    .card-value {
        font-size: 1.5rem;
        font-weight: 700;
    }

    .context {
        background: white;
        padding: 1rem;
        border-radius: 0.5rem;
        margin-bottom: 2rem;
        display: flex;
        gap: 2rem;
        flex-wrap: wrap;
    }

    .gates-section, .issues-section {
        background: white;
        padding: 1.5rem;
        border-radius: 0.5rem;
        margin-bottom: 2rem;
        box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }

    .gates-section h2, .issues-section h2 {
        font-size: 1.25rem;
        margin-bottom: 1rem;
        padding-bottom: 0.5rem;
        border-bottom: 1px solid #e5e7eb;
    }

    .gates-grid {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
        gap: 1rem;
    }

    .gate-card {
        border: 1px solid #e5e7eb;
        border-radius: 0.5rem;
        padding: 1rem;
        position: relative;
    }

    .gate-card-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 0.5rem;
    }

    .gate-name {
        font-weight: 600;
    }

    .gate-status {
        padding: 0.25rem 0.5rem;
        border-radius: 0.25rem;
        font-size: 0.75rem;
        color: white;
    }

    .gate-details {
        font-size: 0.875rem;
        color: #6b7280;
    }

    .score-bar {
        height: 4px;
        background: #e5e7eb;
        border-radius: 2px;
        margin-top: 0.5rem;
        overflow: hidden;
    }

    .score-fill {
        height: 100%;
        border-radius: 2px;
        transition: width 0.3s ease;
    }

    .issues-table {
        width: 100%;
        border-collapse: collapse;
    }

    .issues-table th, .issues-table td {
        padding: 0.75rem;
        text-align: left;
        border-bottom: 1px solid #e5e7eb;
    }

    .issues-table th {
        background: #f9fafb;
        font-weight: 600;
        font-size: 0.875rem;
    }

    .severity-badge {
        padding: 0.125rem 0.5rem;
        border-radius: 0.25rem;
        font-size: 0.75rem;
        font-weight: 500;
    }

    .severity-critical { background: #fef2f2; color: #dc2626; }
    .severity-high { background: #fff7ed; color: #ea580c; }
    .severity-medium { background: #fefce8; color: #ca8a04; }
    .severity-low { background: #eff6ff; color: #2563eb; }
    .severity-info { background: #f3f4f6; color: #6b7280; }

    .chart-section {
        background: white;
        padding: 1.5rem;
        border-radius: 0.5rem;
        margin-bottom: 2rem;
        box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }

    .chart-container {
        position: relative;
        height: 300px;
    }

    .footer {
        text-align: center;
        color: #9ca3af;
        font-size: 0.875rem;
        margin-top: 2rem;
    }
</style>
"""

    def _get_chart_script(self) -> str:
        """Get Chart.js script tag."""
        return '<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>'

    def _get_chart_section(self, result: PipelineResult) -> str:
        """Generate chart section HTML."""
        return """
<section class="chart-section">
    <h2>Score Distribution</h2>
    <div class="chart-container">
        <canvas id="scoresChart"></canvas>
    </div>
</section>
"""

    def _get_chart_init(self, result: PipelineResult) -> str:
        """Generate Chart.js initialization script."""
        labels = [g.gate_name for g in result.gates if g.status != GateStatus.SKIPPED]
        scores = [g.score for g in result.gates if g.status != GateStatus.SKIPPED]
        colors = [self.STATUS_COLORS.get(g.status, "#6b7280") for g in result.gates if g.status != GateStatus.SKIPPED]

        return f"""
<script>
    const ctx = document.getElementById('scoresChart').getContext('2d');
    new Chart(ctx, {{
        type: 'bar',
        data: {{
            labels: {labels},
            datasets: [{{
                label: 'Score',
                data: {scores},
                backgroundColor: {colors},
                borderRadius: 4,
            }}]
        }},
        options: {{
            responsive: true,
            maintainAspectRatio: false,
            scales: {{
                y: {{
                    beginAtZero: true,
                    max: 10,
                    grid: {{
                        color: '#e5e7eb'
                    }}
                }},
                x: {{
                    grid: {{
                        display: false
                    }}
                }}
            }},
            plugins: {{
                legend: {{
                    display: false
                }}
            }}
        }}
    }});
</script>
"""

    def _generate_gate_cards(self, result: PipelineResult) -> str:
        """Generate gate result cards HTML."""
        cards = []

        for gate in result.gates:
            status_color = self.STATUS_COLORS.get(gate.status, "#6b7280")
            score_percent = (gate.score / 10) * 100

            card = f"""
<div class="gate-card">
    <div class="gate-card-header">
        <span class="gate-name">{gate.gate_name}</span>
        <span class="gate-status" style="background-color: {status_color}">{gate.status.value.upper()}</span>
    </div>
    <div class="gate-details">
        <div>Score: {gate.score:.1f}/10 | Time: {gate.execution_time_ms:.0f}ms</div>
        <div>{gate.message}</div>
    </div>
    <div class="score-bar">
        <div class="score-fill" style="width: {score_percent}%; background-color: {status_color}"></div>
    </div>
</div>
"""
            cards.append(card)

        return "\n".join(cards)

    def _generate_issues_table(self, result: PipelineResult) -> str:
        """Generate issues table HTML."""
        all_issues = []

        for gate in result.gates:
            for issue in gate.issues[:10]:
                all_issues.append((gate.gate_name, issue))

        if not all_issues:
            return "<p>No issues found.</p>"

        rows = []
        for gate_name, issue in all_issues[:50]:
            severity_class = f"severity-{issue.severity.value}"
            row = f"""
<tr>
    <td><span class="severity-badge {severity_class}">{issue.severity.value.upper()}</span></td>
    <td>{gate_name}</td>
    <td>{issue.file}:{issue.line or ''}</td>
    <td>{issue.rule}</td>
    <td>{issue.message}</td>
</tr>
"""
            rows.append(row)

        return f"""
<table class="issues-table">
    <thead>
        <tr>
            <th>Severity</th>
            <th>Gate</th>
            <th>Location</th>
            <th>Rule</th>
            <th>Message</th>
        </tr>
    </thead>
    <tbody>
        {"".join(rows)}
    </tbody>
</table>
"""
