# Re-export from _deprecated for backward compatibility
from ._deprecated.learning_models import (
    AgentMessage,
    BionicReadingResult,
    BlackboardEntry,
    CulturalContext,
    FelderDimension,
    Flashcard,
    FSRSCard,
    HybridLearningProfile,
    LearningSession,
    LearningStyleType,
    MorphologyAnalysis,
    Question,
    SimplificationLevel,
    Student,
    TurkishZPDRange,
    create_sample_hybrid_profile,
    create_sample_student,
    create_sample_zpd_range,
)

__all__ = [
    "AgentMessage",
    "BionicReadingResult",
    "BlackboardEntry",
    "CulturalContext",
    "FSRSCard",
    "FelderDimension",
    "Flashcard",
    "HybridLearningProfile",
    "LearningSession",
    "LearningStyleType",
    "MorphologyAnalysis",
    "Question",
    "SimplificationLevel",
    "Student",
    "TurkishZPDRange",
    "create_sample_hybrid_profile",
    "create_sample_student",
    "create_sample_zpd_range",
]
