@echo off
REM TypeScript Type Generation Script for KIRO2 (Windows)
REM Generates TypeScript types from FastAPI OpenAPI schema

echo ======================================
echo KIRO2 TypeScript Type Generation
echo ======================================
echo.

REM Configuration
set BACKEND_URL=http://localhost:8000
set OPENAPI_URL=%BACKEND_URL%/openapi.json
set BACKEND_SCHEMA=backend\openapi.json
set OUTPUT_FILE=frontend\src\types\api.generated.ts

echo [1/4] Checking for OpenAPI schema...

REM Check if backend openapi.json exists
if exist "%BACKEND_SCHEMA%" (
    echo [OK] Found OpenAPI schema at: %BACKEND_SCHEMA%
    set SCHEMA_SOURCE=%BACKEND_SCHEMA%
    goto install_deps
)

echo [WARNING] OpenAPI schema not found at: %BACKEND_SCHEMA%
echo Attempting to fetch from running backend server...

REM Check if backend is running
curl -s -o nul %BACKEND_URL%/health
if %errorlevel% equ 0 (
    echo [OK] Backend server is running
    set SCHEMA_SOURCE=%OPENAPI_URL%
    goto install_deps
) else (
    echo [ERROR] Backend server is not running and openapi.json not found
    echo Please either:
    echo   1. Start backend: cd backend ^&^& uvicorn main:app --reload
    echo   2. Generate schema: cd backend ^&^& python export_openapi_schema.py
    exit /b 1
)

:install_deps
echo.
echo [2/4] Installing openapi-typescript...

REM Install openapi-typescript if not already installed
call npm list openapi-typescript >nul 2>&1
if %errorlevel% neq 0 (
    echo Installing openapi-typescript as dev dependency...
    call npm install --save-dev openapi-typescript
    echo [OK] Installed openapi-typescript
) else (
    echo [OK] openapi-typescript already installed
)

echo.
echo [3/4] Generating TypeScript types...

REM Create output directory if it doesn't exist
if not exist "frontend\src\types" mkdir "frontend\src\types"

REM Generate types
call npx openapi-typescript "%SCHEMA_SOURCE%" --output "%OUTPUT_FILE%" --export-type --path-params-as-types

if %errorlevel% neq 0 (
    echo [ERROR] Type generation failed
    exit /b 1
)

echo [OK] TypeScript types generated successfully!

echo.
echo [4/4] Adding header comments...

REM Add header comment to generated file
(
echo /**
echo  * Auto-generated TypeScript types from KIRO2 Backend OpenAPI Schema
echo  *
echo  * Generated: %date% %time%
echo  * Source: %SCHEMA_SOURCE%
echo  *
echo  * DO NOT EDIT THIS FILE MANUALLY!
echo  * To regenerate: npm run generate:types
echo  *
echo  * KIRO2 - Türkiye Üniversite Sınavları Hazırlık Platformu
echo  * Backend-Frontend Type Safety Automation
echo  */
echo.
type "%OUTPUT_FILE%"
) > "%OUTPUT_FILE%.tmp"

move /y "%OUTPUT_FILE%.tmp" "%OUTPUT_FILE%" >nul

echo [OK] Header added to generated types

echo.
echo ======================================
echo [OK] Type Generation Complete!
echo ======================================
echo.
echo Generated file: %OUTPUT_FILE%

for %%A in ("%OUTPUT_FILE%") do echo File size: %%~zA bytes

echo.
echo Next steps:
echo   1. Import types in your services:
echo      import type { components } from '@/types/api.generated';
echo   2. Use type-safe API client:
echo      type User = components['schemas']['Kullanici'];
echo   3. Update frontend services to use generated types
echo.
