#!/bin/bash

# TypeScript Type Generation Script for KIRO2
# Generates TypeScript types from FastAPI OpenAPI schema
#
# Usage:
#   bash scripts/generate-types.sh
#
# Prerequisites:
#   - Backend server must be running OR openapi.json must exist
#   - npm package 'openapi-typescript' must be installed

set -e  # Exit on error

echo "======================================"
echo "KIRO2 TypeScript Type Generation"
echo "======================================"
echo ""

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Configuration
BACKEND_URL="http://localhost:8000"
OPENAPI_URL="${BACKEND_URL}/openapi.json"
BACKEND_SCHEMA="backend/openapi.json"
OUTPUT_FILE="frontend/src/types/api.generated.ts"

echo -e "${BLUE}[1/4] Checking for OpenAPI schema...${NC}"

# Check if backend openapi.json exists
if [ -f "$BACKEND_SCHEMA" ]; then
    echo -e "${GREEN}✓ Found OpenAPI schema at: $BACKEND_SCHEMA${NC}"
    SCHEMA_SOURCE="$BACKEND_SCHEMA"
else
    echo -e "${YELLOW}⚠ OpenAPI schema not found at: $BACKEND_SCHEMA${NC}"
    echo -e "${BLUE}Attempting to fetch from running backend server...${NC}"

    # Check if backend is running
    if curl -s -o /dev/null -w "%{http_code}" "$BACKEND_URL/health" | grep -q "200"; then
        echo -e "${GREEN}✓ Backend server is running${NC}"
        SCHEMA_SOURCE="$OPENAPI_URL"
    else
        echo -e "${RED}✗ Backend server is not running and openapi.json not found${NC}"
        echo -e "${YELLOW}Please either:${NC}"
        echo -e "  1. Start backend: ${BLUE}cd backend && uvicorn main:app --reload${NC}"
        echo -e "  2. Generate schema: ${BLUE}cd backend && python export_openapi_schema.py${NC}"
        exit 1
    fi
fi

echo ""
echo -e "${BLUE}[2/4] Installing openapi-typescript...${NC}"

# Install openapi-typescript if not already installed
if ! npm list openapi-typescript > /dev/null 2>&1; then
    echo -e "${YELLOW}Installing openapi-typescript as dev dependency...${NC}"
    npm install --save-dev openapi-typescript
    echo -e "${GREEN}✓ Installed openapi-typescript${NC}"
else
    echo -e "${GREEN}✓ openapi-typescript already installed${NC}"
fi

echo ""
echo -e "${BLUE}[3/4] Generating TypeScript types...${NC}"

# Create output directory if it doesn't exist
mkdir -p "$(dirname "$OUTPUT_FILE")"

# Generate types
npx openapi-typescript "$SCHEMA_SOURCE" \
    --output "$OUTPUT_FILE" \
    --export-type \
    --path-params-as-types

echo -e "${GREEN}✓ TypeScript types generated successfully!${NC}"

echo ""
echo -e "${BLUE}[4/4] Adding header comments...${NC}"

# Add header comment to generated file
HEADER="/**
 * Auto-generated TypeScript types from KIRO2 Backend OpenAPI Schema
 *
 * Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
 * Source: $SCHEMA_SOURCE
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 * To regenerate: npm run generate:types
 *
 * KIRO2 - Türkiye Üniversite Sınavları Hazırlık Platformu
 * Backend-Frontend Type Safety Automation
 */

"

# Prepend header to generated file
echo "$HEADER$(cat "$OUTPUT_FILE")" > "$OUTPUT_FILE"

echo -e "${GREEN}✓ Header added to generated types${NC}"

echo ""
echo "======================================"
echo -e "${GREEN}✓ Type Generation Complete!${NC}"
echo "======================================"
echo ""
echo -e "${BLUE}Generated file:${NC} $OUTPUT_FILE"
echo -e "${BLUE}File size:${NC} $(wc -c < "$OUTPUT_FILE" | xargs) bytes"
echo -e "${BLUE}Lines:${NC} $(wc -l < "$OUTPUT_FILE" | xargs) lines"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo -e "  1. Import types in your services:"
echo -e "     ${BLUE}import type { components } from '@/types/api.generated';${NC}"
echo -e "  2. Use type-safe API client:"
echo -e "     ${BLUE}type User = components['schemas']['Kullanici'];${NC}"
echo -e "  3. Update frontend services to use generated types"
echo ""
